/**
 * Phase 14.2 — BFF catch-all for better-auth.
 *
 * Forwards every /api/auth/better/<...> path to Express's
 * /api/auth/better/<...> mount. Same path on both sides so
 * better-auth's internal route table matches the URL the browser
 * sees, and OAuth redirect URLs generated by better-auth resolve
 * correctly regardless of which side of the BFF hop they originate
 * on.
 *
 * Cookies set by Express's response (better-auth's session cookie
 * after successful Google sign-in) are forwarded back via
 * forwardToApi's getSetCookie() passthrough — same pattern as our
 * existing JWT cookie from Phase 13.2. The browser scopes the
 * cookie to metu.fly.dev (the BFF host) because Express deliberately
 * omits the Domain attribute.
 *
 * GET handles OAuth-flow redirects (sign-in start, callback);
 * POST handles JSON-body endpoints (sign-out, link-account).
 * better-auth uses both verbs across its catch-all surface.
 */
import { type NextRequest } from "next/server";
import { forwardToApi } from "@/lib/server/proxy";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function targetPath(allSegments: string[], search: string) {
  const path = allSegments.length ? `/${allSegments.join("/")}` : "";
  return `/api/auth/better${path}${search}`;
}

export async function GET(req: NextRequest, { params }: { params: { all: string[] } }) {
  return forwardToApi(req, targetPath(params.all, req.nextUrl.search || ""));
}
export async function POST(req: NextRequest, { params }: { params: { all: string[] } }) {
  return forwardToApi(req, targetPath(params.all, req.nextUrl.search || ""));
}
export async function PATCH(req: NextRequest, { params }: { params: { all: string[] } }) {
  return forwardToApi(req, targetPath(params.all, req.nextUrl.search || ""));
}
export async function DELETE(req: NextRequest, { params }: { params: { all: string[] } }) {
  return forwardToApi(req, targetPath(params.all, req.nextUrl.search || ""));
}
