"""Phase 38 - hash -> casual rewritten body mapping for filter-repo."""
COMMIT_OVERRIDES = {
    # ===== short/empty bodies (skip with empty string) =====
    "d80351c": "",
    "4e071cc": "",
    "f28374c": "",
    "8a03908": "",
    "9ffd357": "",
    "07ea283": "",
    "4c591b5": "",
    "66d9f02": "",
    "a15f403": "",
    "ae56d89": "",
    "28d059d": "",
    "e274d3d": "",
    "9be74da": "",
    "dae2099": "",
    "7b07978": "",
    "c68fb74": "",
    "808d796": "",
    "dcff307": "",
    "c283ca8": "",
    "26b5ea9": "",
    "d41aac6": "",
    "7459830": "",
    "1017699": "",
    "635f669": "",
    "416e6af": "",
    "7854acd": "",
    "a0ff159": "",
    "b08c41c": "",
    "faccb43": "",
    "5a4ae2f": "",
    "bbf7fdf": "",
    "d8825f5": "",
    "969ebf2": "",
    "daf8f12": "",
    "9d74a2c": "",

    # ===== rewrites for long bodies =====
    "7b2ca45": "buyer persona test ครอบ checkout demo-mode -> license/download ส่วน stripe iframe ข้าม CI flaky",
    "54a6c3f": "ER drag/zoom feel ดีขึ้น + tech stack page รื้อใหม่เป็น infographic แบ่ง 8 หมวด",
    "491007a": "2 buyers กด checkout พร้อมกันแล้ว qty ลบได้ - ใส่ conditional update + rollback ถ้าหมด stock",
    "ae20a6a": "Stripe TH default payout รายสัปดาห์ - เพิ่มปุ่มขอเองสำหรับ demo",
    "f512775": "modal นั่งใน components/ ตั้งแต่ phase 23.3 ยังไม่ได้ wire - ใส่ refund + revoke-all ก่อน",
    "071d0da": "doc พูดถึง master coupon มาตลอดแต่ schema NOT NULL store_id ทำให้สร้างไม่ได้",
    "d98e704": "หลังจ่ายผ่าน stripe ไม่มี download/key ส่ง - finalizeOrder + email receipt + snapshot ลง order_item",
    "2870128": "tier-1 ก่อน defense - coupon usage unique, ER 1:1 PK-as-FK, ดับ ghost categories จาก phase 26",
    "abe414d": "express ใส่ helmet ตั้งแต่ p22 แต่ BFF ไม่มี header เลย - HSTS/CSP/XFO/cookie attrs",
    "905dec7": "Stripe TH ห้าม platform loss-liable - ต้องใช้ controller shape recipient model + seed script",
    "823d3da": "3 prod bugs หลัง phase 26+27: google login 404, addToCart prisma fail, banner เตือน stripe ยังไม่ onboard",
    "c6b1ec8": "/seller pages เรียก API ตรงผ่าน NEXT_PUBLIC_API_BASE ที่ไม่ได้ set + cookie ว่าง = 401",
    "0f65ad8": "TH ไม่มี Marketplace model - ต้อง direct charge + Stripe-Account header แทน",
    "d1c9ec0": "scope doc v3 framing เป็น phase changelog, อาจารย์อยากได้ scope จริง - rewrite v4",
    "b1a2e07": "user feedback บอก ER ดูแปลก - threshold เก่าส่ง edge ไป highway เยอะไป กว้างเป็น <= 4",
    "3a4a5b3": "ER PNG ใน docx 3 issues: wallet column ว่าง, polyline ทะลุ card, USERS hub markers ทับกัน",
    "6b5c45d": "regen ER post-phase-27 + build docx v3 ใหม่ - drop wallet, ใส่ stripe column, พังจาก v2 leftovers",
    "735dc86": "ย้าย Neon -> Supabase Singapore (region เดียวกับ Fly sin) - ฟรีกว่าและ pooler 2 ports สบายขึ้น",
    "a08f592": "แทน promptpay/coin layer ด้วย stripe connect - stripe เป็น source of truth ไม่เพิ่ม table",
    "52a8e3b": "slim schema ก่อน demo - drop messaging, q&a, stock alert, wallet/topup/withdrawal เพราะ phase 27 จะใช้ stripe",
    "a4a59ff": "polyline midX bend ลงกลาง column ที่ไม่เกี่ยว ทำให้เส้นทะลุ card อื่น",
    "49b5374": "dagre LR ranker บีบ 35 entities เป็น column สูง 6500px - hand-roll category-grid placer",
    "90fdef3": "SVG export missing crow-foot markers + PNG ขึ้น SecurityError จาก foreignObject - + layout overcrowded",
    "ee40bc7": "Lucidchart trial หมดใน 7 วัน + ไม่ sync schema - render เอง derive จาก schema.prisma ตรงๆ",
    "67036c6": "session cookie ที่ขโมยมาไม่ควรใช้ทำ sensitive action ได้ทั้ง session - ขอ TOTP สดใน 15 นาที",
    "e0a9419": "23.1 Sessions UI - backend live มา weeks แล้ว ยังไม่มี UI ให้ user ดู device ตัวเอง 23.2 เติม audit gap",
    "d0c6242": "migration เขียน FK ชี้ users(user_id) แต่ใช้ \"user\" เลย P3018 บน Fly - SQL hand-written hazard",
    "4bbe4b8": "3 wins ก่อน TOTP step-up: rate limiter user-keyed, helmet@8 + CSP, profanity บน message body",
    "ffa063b": "ต่อจาก 20.1 - seller cash out coin ผ่าน admin queue (manual transfer ไม่ใช้ processor)",
    "fc27b68": "checkout แสดงราคาเป็น coin แต่ไม่ได้ขยับเงินจริง - ทำ wallet เป็น money rail + platform fee",
    "a49a2c9": "/admin/architecture sidebar link ตายมาตลอด page ไม่เคยมี - แทนด้วย ER (lucidchart embed) + tech stack",
    "cd2b36b": "chatEnabled flag มีตั้งแต่ p17 แต่ wire แค่ TopNav - ปิดได้จริง 3 layers (page/entry/api)",
    "836f1c6": "Google OAuth provider ขึ้นแล้วตั้งแต่ p17.x เหลือ docs + ConnectedAccounts UI ให้ unlink ได้",
    "4e73f4c": "buyer แลก baht เป็น coin ผ่าน promptpay QR + slip จริงได้แล้ว + admin review queue สำหรับ slip ที่ verify ไม่ผ่าน",
    "8265c64": "user request: \"อยากให้กดปิดหรือเปิดระบบ favorite ได้เหมือนกัน\" - flag ตัวที่ 3 ตามรอย walletEnabled/chatEnabled",
    "e965da6": "user แจ้ง \"เชื่อม login ด้วย google ไม่ได้\" - prod ไม่มี secrets, button ชี้ 404 มาตลอด ซ่อนถ้า env ไม่ครบ",
    "8f6f780": "วาง dep + util สำหรับ slip verify - jsqr อ่าน QR EMVCo เร็วกว่า OCR และไม่ต้องใช้ tesseract 10MB",
    "f070aa2": "ทุก surface แสดงเป็น coin (1 baht = 10 coin) - DB ยังเก็บคู่กันไว้ทั้ง 2 column",
    "c175141": "วาง data + service foundation สำหรับ coin economy - กั้น flag default OFF ทุก surface ใหม่",
    "436d012": "login ผ่านแล้ว /auth/me คืน 401 - better-auth findFirst where {id} แต่ schema เราใช้ userId ต้อง rewrite ทั้ง input + result",
    "d1f08ed": "commit ก่อนเพิ่ม updatedAt แล้วยังขึ้น \"Credential account not found\" - better-auth hard-code field=='id' ต้อง proxy mirror userId->id",
    "73fb993": "prod login fail ทุกราย - better-auth select createdAt+updatedAt แต่ table เก่ามีแค่ created_date - migration + field map",
    "81824cf": "rebuild login form clean step-machine + drop dead BFF auth helpers + retry migration ที่ rolled-back ไป",
    "808cd65": "ลบ JWT cookie ทิ้งให้ better-auth ดูแล session อย่างเดียว - 1 cookie 1 config 1 secret",
    "e595e17": "TOTP 2FA universal ผ่าน otplib - enroll ใน /profile/edit, ใส่ 6 หลักหลัง password check ทุก login",
    "218f0fc": "admin มีทางสายกลาง - ซ่อน store จาก public ทุกที่ แต่ row+products+history ยังอยู่ flip กลับได้",
    "7bc2daf": "phase 15 จบ - admin บังคับ user reset password ตอน login ครั้งหน้า + bonus แก้ google button หาย",
    "36f9de3": "session ที่ขโมยมาไม่ควรเปลี่ยน password ได้ - user ที่ verify เบอร์แล้วต้องใส่ OTP สดทุกครั้งที่ทำ sensitive op",
    "0440c83": "audit_log ไม่รู้เลยว่า request มาจาก IP/UA ไหน - เพิ่ม 2 column nullable + ส่ง req ใน admin destructive flows",
    "2247f9a": "user เห็นทุก device ที่ login better-auth ของตัวเองได้ + revoke per-row หรือ all-others",
    "68980ea": "กัน credential stuffing + signup bot + SMS spend - sliding window in-memory per-IP, ไม่ใช้ redis",
    "44ab6d0": "user set เบอร์ใน /profile/edit แล้วขอ OTP 6 หลัก - transport แบบเสียบได้ (console dev / twilio prod)",
    "c54fa62": "ปิด security gap p14.2 - ก่อนหน้านี้ google sign-in สร้าง user ใหม่เงียบๆ ทุกครั้งที่ email ชนของเก่า",
    "af72290": "google user มี password=NULL - ให้ตั้ง password แรกได้จาก /profile/edit แล้วใช้ email+password ก็ได้",
    "02b6035": "Continue with Google work end-to-end - middleware DUAL-STACK เพื่อให้ test เก่า 112 ตัวยังเขียวอยู่",
    "b9a0a55": "twin ของ ad261be - builder stage เห็น better-auth แล้วแต่ runner ยังไม่มี ทำให้ start ไม่ขึ้น",
    "ad261be": "ROOT CAUSE deploy fail 4 รอบ - dockerfile copy แค่ /app/node_modules ไม่ copy workspace local",
    "9750988": "fix รอบ 3 - การ resolve 2 hop ผ่าน subpath export พังบน alpine + npm ci - import ตรงๆ ก็จบ",
    "f47c402": "fix รอบ 2 - --ignore-scripts กิน install hook ของ better-auth ทำ nested adapter หาย ปักเป็น direct dep แทน",
    "35eec2d": "phase 14.1 deploy fail - --ignore-scripts ตัด nested adapter ของ better-auth ทิ้ง ลบทิ้งได้เพราะ server ไม่ต้องการ",
    "a49c2ec": "วาง plumbing better-auth - schema/account/session/verification + catch-all mount ก่อน UI ใช้",
    "4954044": "phase 13 จบ - 4 layered modules ทุก resource (route/controller/service/model) ไม่มี flat router เหลือ",
    "400e95e": "9 admin endpoints ไป layered express - role gate ครั้งเดียวที่ router level ทุก handler assume admin context",
    "fd74753": "user ดู /admin/changelog แล้วเห็น 2 ปัญหา - commit link 404 เพราะ placeholder ไม่ใช่ SHA จริง + README stale",
    "73a33ca": "ครึ่งหลัง p13.9 - 10 endpoint write ของ seller ไป express หมด + special become-seller ที่ต้อง auth แต่ไม่ต้อง requireStore",
    "0fc388f": "ครึ่งแรก p13.9 - read endpoint ของ seller dashboard 6 ตัวไป express + middleware requireStore ใหม่",
    "0cbfa72": "buyer-seller messaging ไป express - postgres-only path, mongo sidecar เลื่อนเป็น followup",
    "bc5709c": "join-table 2 อันไป express - idempotent ผ่าน @@unique เดิม subscribe ซ้ำเคลียร์ notifiedAt",
    "1bdc9bf": "เติม 4 หัวข้อจาก lec 10 ที่ codebase ไม่มี - trigger/view/role/check, viva ตอบได้ทุก slide",
    "80f60ba": "q&a + admin moderation ไป express - sellers ตอบได้แค่ผ่าน /answer ไม่ใช่ edit field กันสับ stamp ผิด",
    "9fba3a1": "reviews + admin moderation ไป express - sellers ห้ามแก้รีวิวสินค้าตัวเองกันปั่น",
    "3f63d88": "orders + checkout ไป express - 7-step transaction, decimal math กัน float loss, partial checkout reparent กลับ cart",
    "accf4bd": "ปิด p13.2 deferral - forgot/reset password ไป express + email facade port มาด้วย",
    "95b0194": "cart + coupons ไป express - merge-on-duplicate, ownership 404 ไม่ leak, validate ladder",
    "9be9fa7": "currentUser() คืน row เต็มมี bcrypt hash, /me forward ตรงไม่ strip - login/register strip แล้ว แต่ /me bypass",
    "0942fcd": "auth ไป express - express owns Set-Cookie, BFF forward ผ่าน proxy origin trick ให้ scope กับ metu.fly.dev",
    "22b79ba": "split monolith เป็น 2 fly apps: metu (BFF/UI) + metu-api (express/prisma) - catalog vertical slice แรก",
    "dcbfa5a": "QA round 3 - card บน /admin/changelog + comment ทำให้ชัดว่า suppressHydrationWarning ใช้สำหรับ theme bootstrap",
    "907ee5b": "พยายามแรก suppressHydrationWarning ไม่ช่วย - root cause คือ multi priority Image stack on หน้าเดียว",
    "22a1325": "QA #3 เจอ react #418/#422 ทุก public page - theme bootstrap script เปลี่ยน html className ก่อน hydrate",
    "b787f66": "S8 review ขอแยก self-deleted vs admin-removed-for-cause ใน schema - ก่อนหน้าเก็บใน meta json query ไม่ได้",
    "1b98358": "Phase 11 · F19 + Phase 11.2 cards บน /admin/changelog",
    "aba77ed": "/browse mobile ต้อง scroll ผ่าน 4 filter cards ก่อนเจอ product - bottom-sheet pill ที่ top, scroll preserve ตอน toggle",
    "b873994": "p11.1 ตัด overflow แล้วยังขึ้น \"฿45,6...\" ellipse กลางตัวเลข - ใช้ K/M/B compact แทน",
    "912fc08": "S8 ติงว่า query ที่ filter deleted_at IS NULL จะ scan เต็ม เมื่อ store live ทะลุ 500 - partial index ครอบ live path",
    "362853d": "/browse desktop กว้างๆ มี 6 cards แถวเดียวแต่ใบสุดท้ายโดนตัด + StatCard highlight font ทะลุ ¼ viewport",
    "cb79ade": "/not-found ยัง 200 หลัง dynamic - next 14 routing ตามชื่อ literal ขัดกับ convention ลบ page route ทิ้งไปเลย",
    "0daa1c2": "/not-found 200 ทั้งที่ notFound() เพราะ next prerender ไป build time - force-dynamic ให้รัน per request",
    "0426dd3": "9 findings round 2 - soft-delete predicate ทุกที่, profanity guard, cart badge realtime, /not-found 404 จริง",
    "f0b0f09": "F4/F10/F13 - image priority, cart thumb priority, drop /admin/stores HTTP hop ใช้ helper ตรง",
    "46923e3": "F9/F17/F18 - coupon hint i18n, changelog \"today\" count, favourites -> favorites (US spelling)",
    "1320bde": "F7/F16 - DollarSign อ่านเป็น USD ในใจคนไทย เปลี่ยนเป็น Banknote + home stat grid equalize",
    "451d19c": "F6/F11/F15 - multi-role badge, drop sort apply (auto-submit แล้ว), Avatar primitive deterministic HSL",
    "1f6f15c": "Sort dropdown auto-submit เปลี่ยน + reset page=1 + .gitignore เพิ่ม reports/ shots/",
    "3a872a9": "9 findings - userId 41 ใน brief ผิด เป็น user 53 จริง, slug resolver, junk store cleanup, counter unify",
    "49d8ce4": "4 cohesion fixes - browse grid orphan, drop THB pill, sellers stat-card flat, lock banner ใช้ mint info",
    "a7599bb": "6 findings - guest state hardening + StoreNameLink + ConfirmDialog primitive แทน window.confirm 6 จุด",
    "1ca91a9": "F2/F7/F17/F20/F24/F25 - empty state friendlier, locale-pinned date Asia/Bangkok",
    "d60f2fc": "/profile/edit skeleton flash - parent loading.tsx shape ไม่ตรง real form, country fetch serial",
    "6521337": "DIGITAL hero word บน light mode contrast 1.5:1 ตก WCAG AA - light override สำหรับ bg-hero-radial + text-light-sweep",
    "19cf907": "user feedback \"UI bug ตอนสั่ง order เสร็จซูมจนล้นจอ\" + อยากได้เสียงเข้ากับ confetti",
    "0cc9a62": "user feedback \"อัพเดทหน้า /features ให้เข้ากับอัพเดทล่าสุด + ทำให้เห็นภาพมากขึ้น\"",
    "9333bc2": "(1) server timestamp render เป็น UTC - set TZ=Asia/Bangkok (2) sound เงียบบน prod - SoundToggle SSR state ไม่ตรง + autoplay policy",
    "55d6aa5": "user feedback \"ช่องใส่รูปมันใหญ่ไปหน่อยนะ\" - empty 64x64 + filled 80x80 แทน aspect-[5/2] ที่กิน 360px",
    "4f6abe4": "audit เจอ buyer ไม่มีทางเข้า chat กับ store เลย sellers มี sidebar - parity ทั้งสองฝั่ง",
    "900f497": "/admin pages ที่เหลือใช้ DataTable + ActionRow แทน styled HTML table look 2020",
    "b3fac9f": "rewrite seller forms ทุกตัวให้ใช้ primitives จาก step 2 - drop pattern \"glass card cramped grid-cols-4\"",
    "7f2a6c2": "วาง foundation primitives ให้ step 3 agents ใช้ - กัน \"ทุก form เป็น glass card cramped\"",
    "44ad5e7": "user request: admin ต้องจัดการ content บนหน้า store ได้ - delete/edit reviews + Q&A audit-logged",
    "906c789": "เดิม hard-code \"Seller answered\" - admin ตอบได้ด้วย ป้ายผิด, ใส่ branch ตาม role + coral accent",
    "ab77964": "rebrand surface ที่ขายของ - product/store/cart/seller/admin ใช้ surface tokens ใหม่",
    "74e4e5b": "rebrand marketing surfaces - ฆ่า symmetric 4-col AI tell, asymmetric grid + rhythm",
    "df60b2e": "6 ux papercut - mobile grid, profile-edit stack, variant trash hint",
    "121d465": "5 audit bugs - minRating pagination, cart busy reset, save-for-later toast, coupon guard, sort cast",
    "37ec482": "rebrand cards - ProductCard variants, mint Badge, asymmetric StatCard, FlatCard primitive",
    "75f3a36": "rebrand shell - TopNav 3 visual groups, Footer asymmetric, Prompt thai font",
    "83e1dcd": "วาง design system foundation - mint+coral, surface variants, motion, Prompt slot",
    "51e520e": "G.39 vitest 26 ตัว pure helpers + G.40 playwright 4 persona vs live deploy",
    "5f7937c": "F.36 sentry env-gated, F.37 plausible cookie-free, F.38 /health page server-rendered",
    "1b2c541": "E.29 light mode inline bootstrap script ก่อน hydrate + E.30 i18n provider เอง ไม่พึ่ง next-intl",
    "e344722": "E.1 manifest+sitemap+robots, E.2 skip-to-content+focus-trap, E.3 better 404",
    "b0c2e03": "force-static prerender admin layout เลย bake redirect login ไว้ในหน้า static - admin จริงก็โดนเด้ง",
    "b876fcb": "requireAuth/getMe เช็ค role จาก JWT cookie ตอน issue - admin โดน demote แก้ตัวเองไม่ได้เพราะเข้า /admin ไม่ได้",
    "d0be3ef": "static page server-rendered list ทุก batch ที่ ship วันนี้ + commit SHA + checklist - หลัง admin role gate",
    "d17f282": "3 small UX wins - become-seller demote admin ตัวเอง, admin pill ใน TopNav, smooth scroll + scroll-padding",
    "1c4e3c9": "7 buyer features + 4 schema add - Q&A, sample, related, compare, gift, rating filter, restock alert",
    "c566a86": "7 seller tools + 1 migration - duplicate, pause, inbox, coupon report, csv, low-stock, bulk edit",
    "9d97a96": "7 quick win ไม่ต้อง migration - recently viewed, share, social proof, save-for-later, shortcuts, profile edit, change password",
    "a9f6e85": "rate-limit /api/auth/* + reset password 30min token + audit log everywhere + soft-delete user/store/product + Turnstile + GDPR export",
    "b03d981": "1gb ($5.70) เกิน free credit $5 - กลับ 512mb ($3.88) เพื่อให้ฟรีต่อ",
    "a2df7f7": "user scale Fly machines เป็น 1024MB ใน dashboard - sync repo config กัน next deploy scale ลงไปเอง",
    "a7211e0": "14-20px backdrop blur stack 40 cards บน /browse + sticky topnav recompute ทุก scroll frame - jank",
    "77b921b": "runner stage copy แค่ prisma package ไม่ copy node_modules/.bin - call JS entry ตรงๆ ดีกว่า",
    "2299460": "Fly Launch wizard ตั้ง internal_port=8080 dockerfile เราใช้ 3000 - fly-proxy หา container ไม่เจอ",
    "a3bce13": "3 issues หลัง postinstall fix - public dir ว่าง, experimental key, /register ต้อง force-dynamic",
    "8eb7dd9": "apps/web postinstall รัน prisma generate แต่ deps stage ยังไม่มี schema - --ignore-scripts",
    "6ad49d3": "ย้ายจาก Vercel iad1 -> Fly sin region เดียวกับ Neon - ลด latency 1s/req เหลือ <100ms",
    "edb2eb2": "live deploy รัน iad1 (Virginia) + Neon Singapore = ทุก request เสีย 500-700ms pacific roundtrip - hnd1 ใกล้กว่า",
    "a05830d": "/seller/store/edit POST มา /api/seller/store ตั้งแต่วันแรก แต่ route ไม่เคยมี - 405/404 มาตลอด",
    "6f220a7": "empty cart render \"Popular right now\" grid ใต้ empty card - query fire เฉพาะตอน cart ว่าง",
    "6e1166c": "site เริ่ม slow - keep-warm cron กัน Neon idle, parallel product page, prisma global, unpooled migrate",
    "21b2b3f": "seller refund คำสั่งได้ (เช่น out of stock) - กั้น ownership + status, atomically flip + refund Transaction",
    "30d9a0d": "/orders แตก 4 tab ตาม status bucket + count badge - ใช้ ?tab= query ไม่ใช้ client JS",
    "ad7ceeb": "Web Audio API cue 5 ตัว ไม่ ship file + speaker mute toggle + bubble \"+N added\" rise+fade",
    "4ecaea4": "/seller/analytics 5 query parallel - daily revenue 30d, status mix, top products+buyers, lifetime totals",
    "1871ed6": "/register optional dob+gender+country ใต้ details, /product description expandable, receipt tag chips",
    "ea15b1e": "ProductFavorite table + API + heart UI หลายจุด + /favorites page + TopNav heart icon",
    "6d7e649": "seller flip paid order เป็น fulfilled/cancelled จาก orders inbox - ไม่แตะ pending/refunded (ของ admin)",
    "c12b685": "edit form prefill mirror create form + DELETE 409 ถ้ามี sales (FK lock) + actions column ใน list",
    "04f5208": "variant rows แสดง stock จริง + qty input cap, digital lock 1, pulse animation + flip label \"Added\"",
    "f1f27ed": "checkbox per line สำหรับ partial checkout + typed qty + per-store coupon scope - แก้บัค buy ลบ cart ทั้งกอง",
    "3835748": "หน้า in-app reference list ทุก page แบ่ง guest/buyer/seller/admin - ไว้ใช้ตอน demo + คนใหม่อ่าน",
    "7ff6973": "admin จัดการ users/stores/transactions ในหน้าเดิม - role select, delete (กัน self), refund flip status",
    "7da4fb7": "/api/admin/stats เพิ่ม 14-day series ผ่าน generate_series + recent transactions 10 -> 30 + pure-svg chart",
    "f058142": "DiceBear SVG avatar - next/image ปัด SVG default (XSS) ปลด unoptimized แล้วทุก profile pic พัง",
    "a0b5c67": "หลัง create row ใหม่ destination page server component cache RSC payload เก่า - F5 ถึงเห็น",
    "650fc8d": "swap URL-only input บน images ของ product เป็น FileImageInput - upload ได้หรือ paste URL",
    "21f48cb": "image inputs swap เป็น FileImageInput - upload ได้หรือ paste URL match กับ store flow",
    "1493fea": "P0 bugs จาก QA + review-from-order + store image upload + perf ของ animation ที่กิน CPU",
    "94c02b0": "fix 11 issue จาก QA - 5 missing pages + skeletons + footer/category UX",
    "df27e4a": "port visual จาก reference repo (N0M3KM/metu-platform) - palette/font/glass + product/cart/order rebrand",
    "20f6593": "deprecation warning ชี้ advisory 2025-12-11 - ขึ้น 14.2.35 latest patch ใน line 14.2 ไม่มี breaking",
    "addd611": "client component fall back http://localhost:4000 บน prod - เปลี่ยนเป็น /api/* relative + base URL ตอน server",
    "59b2d11": "phase 1 auth speed 3 DB call รวมเป็น 1 + drop redundant router.refresh / phase 2 themed product images / phase 3 P0 จาก audit",
    "b266354": "first ship - 20 entity prisma schema + thai seed + dark mode + buyer/seller/admin flows + demo accounts",
}
