// AUTO-GENERATED by scripts/generate-commit-timeline.mjs.
// Re-run after each commit batch:  node scripts/generate-commit-timeline.mjs
//
// Drives /admin/timeline. Edit the script, not this file.

export type CommitNode = {
  sha: string;
  shortSha: string;
  dateIso: string; // ISO 8601
  author: string;
  subject: string;
  type: string;    // feat | fix | docs | refactor | test | chore | …
  scope: string | null;
  parents: string;
};

export const COMMIT_TIMELINE: ReadonlyArray<CommitNode> = [
  {
    "sha": "2c7d5333f2050a7e37c6d7df1467a5963ccd58b5",
    "shortSha": "2c7d533",
    "dateIso": "2026-05-04T15:03:08+07:00",
    "author": "Bank",
    "subject": "consolidate api forwarders into a catch-all + share skeleton primitives",
    "parents": "0b0e7d4125793f3d147def39c900c331d4782c03",
    "type": "other",
    "scope": null
  },
  {
    "sha": "0b0e7d4125793f3d147def39c900c331d4782c03",
    "shortSha": "0b0e7d4",
    "dateIso": "2026-05-04T14:53:22+07:00",
    "author": "Bank",
    "subject": "centralise env config + clean up comment noise",
    "parents": "e2bdf0d18e42b8e9f6134a3533f4e0f05333837f",
    "type": "other",
    "scope": null
  },
  {
    "sha": "e2bdf0d18e42b8e9f6134a3533f4e0f05333837f",
    "shortSha": "e2bdf0d",
    "dateIso": "2026-05-04T14:34:49+07:00",
    "author": "Bank",
    "subject": "add regression tests for the security hardening pass",
    "parents": "0ba252adece9d779c7706d35bb3153f7c3e82d24",
    "type": "other",
    "scope": null
  },
  {
    "sha": "0ba252adece9d779c7706d35bb3153f7c3e82d24",
    "shortSha": "0ba252a",
    "dateIso": "2026-05-04T14:02:33+07:00",
    "author": "Bank",
    "subject": "harden otp + license keys, csv export, webhook amount check",
    "parents": "82afb37683becdbe157f9a9e272539ecf835ec71",
    "type": "other",
    "scope": null
  },
  {
    "sha": "82afb37683becdbe157f9a9e272539ecf835ec71",
    "shortSha": "82afb37",
    "dateIso": "2026-05-04T12:26:12+07:00",
    "author": "Bank",
    "subject": "redirect bare host to canonical domain",
    "parents": "2a3562fc33b1acd4f71dc5c8f607a6a2543a836a",
    "type": "other",
    "scope": null
  },
  {
    "sha": "2a3562fc33b1acd4f71dc5c8f607a6a2543a836a",
    "shortSha": "2a3562f",
    "dateIso": "2026-05-04T09:50:17+07:00",
    "author": "Bank",
    "subject": "drop unused style guide and oauth setup notes",
    "parents": "0fc86abe5c247bdf30205f01f754e80dc2b54c50",
    "type": "other",
    "scope": null
  },
  {
    "sha": "0fc86abe5c247bdf30205f01f754e80dc2b54c50",
    "shortSha": "0fc86ab",
    "dateIso": "2026-05-04T09:45:47+07:00",
    "author": "Bank",
    "subject": "remove stale local editor config from tracking",
    "parents": "2676cd8a18e159e51798a5e45f0576f23b5bf742",
    "type": "other",
    "scope": null
  },
  {
    "sha": "2676cd8a18e159e51798a5e45f0576f23b5bf742",
    "shortSha": "2676cd8",
    "dateIso": "2026-05-04T09:43:42+07:00",
    "author": "Bank",
    "subject": "drop old er-v2 diagram and unused planning docs",
    "parents": "2c403a47076738abc7de7c613cc5e8ebf9fc8cb0",
    "type": "other",
    "scope": null
  },
  {
    "sha": "2c403a47076738abc7de7c613cc5e8ebf9fc8cb0",
    "shortSha": "2c403a4",
    "dateIso": "2026-05-03T23:36:26+07:00",
    "author": "Bank",
    "subject": "fix turnstile prop name",
    "parents": "6935b4ee062448c75f7e6e92e5c4dc87232a597c",
    "type": "other",
    "scope": null
  },
  {
    "sha": "6935b4ee062448c75f7e6e92e5c4dc87232a597c",
    "shortSha": "6935b4e",
    "dateIso": "2026-05-03T23:29:05+07:00",
    "author": "Bank",
    "subject": "wire stripe refund into seller + admin refund paths, add captcha to login + forgot-password",
    "parents": "84689460b14f1939b7a00b3b0dc0c4d9e65dfe93",
    "type": "other",
    "scope": null
  },
  {
    "sha": "84689460b14f1939b7a00b3b0dc0c4d9e65dfe93",
    "shortSha": "8468946",
    "dateIso": "2026-05-03T23:18:20+07:00",
    "author": "Bank",
    "subject": "Phase 51 batch 2 — close 6 more bugs from second QA pass",
    "parents": "a3a2242ab96b64c755bc741a7e85594feca43ca5",
    "type": "other",
    "scope": null
  },
  {
    "sha": "a3a2242ab96b64c755bc741a7e85594feca43ca5",
    "shortSha": "a3a2242",
    "dateIso": "2026-05-03T23:08:36+07:00",
    "author": "Bank",
    "subject": "Phase 51 — close 11 security holes from QA pass",
    "parents": "134187ffe60145792b87e80eace67fd6ba7fcfe3",
    "type": "other",
    "scope": null
  },
  {
    "sha": "134187ffe60145792b87e80eace67fd6ba7fcfe3",
    "shortSha": "134187f",
    "dateIso": "2026-05-02T23:24:23+07:00",
    "author": "Bank",
    "subject": "fix(phase-50): cart/checkout availability gate + price sort + sitemap + rating aggregate",
    "parents": "0293dc96958a184ae2eda10a50b079c6a774e146",
    "type": "fix",
    "scope": "phase-50"
  },
  {
    "sha": "0293dc96958a184ae2eda10a50b079c6a774e146",
    "shortSha": "0293dc9",
    "dateIso": "2026-05-02T22:52:32+07:00",
    "author": "Bank",
    "subject": "fix(phase-49): make trusted_device migration idempotent",
    "parents": "34a837ceee55317af5c25a997fab15f9ac40126f",
    "type": "fix",
    "scope": "phase-49"
  },
  {
    "sha": "34a837ceee55317af5c25a997fab15f9ac40126f",
    "shortSha": "34a837c",
    "dateIso": "2026-05-02T22:45:46+07:00",
    "author": "Bank",
    "subject": "feat(phase-49): admin demo email-OTP gate + 7-day trusted devices + single-session",
    "parents": "0a2f2055323e530961d8216846f81940a6975274",
    "type": "feat",
    "scope": "phase-49"
  },
  {
    "sha": "0a2f2055323e530961d8216846f81940a6975274",
    "shortSha": "0a2f205",
    "dateIso": "2026-05-02T16:55:58+07:00",
    "author": "Bank",
    "subject": "fix(phase-48): banned user kick-out + double-check in requireAuth",
    "parents": "a0d37567d39f795152500b9a6bccfbd4a002c3e5",
    "type": "fix",
    "scope": "phase-48"
  },
  {
    "sha": "a0d37567d39f795152500b9a6bccfbd4a002c3e5",
    "shortSha": "a0d3756",
    "dateIso": "2026-05-02T15:59:07+07:00",
    "author": "Bank",
    "subject": "fix(phase-48): tighten IP-ban surface + block self-delete on pending orders",
    "parents": "c414759f048864af7aac935f2ab7543f861fc021",
    "type": "fix",
    "scope": "phase-48"
  },
  {
    "sha": "c414759f048864af7aac935f2ab7543f861fc021",
    "shortSha": "c414759",
    "dateIso": "2026-05-02T14:53:54+07:00",
    "author": "Bank",
    "subject": "feat(phase-48): already-owned guard + useful admin actions + IP ban + GDPR self-delete",
    "parents": "665517015c69f6b52c992948a1f4779db6d08373",
    "type": "feat",
    "scope": "phase-48"
  },
  {
    "sha": "665517015c69f6b52c992948a1f4779db6d08373",
    "shortSha": "6655170",
    "dateIso": "2026-05-02T12:08:59+07:00",
    "author": "Bank",
    "subject": "fix(images): allow Google profile photos in next/image remotePatterns",
    "parents": "643cb63bb30b823fd4a9b3a4850cf55fbefccda3",
    "type": "fix",
    "scope": "images"
  },
  {
    "sha": "643cb63bb30b823fd4a9b3a4850cf55fbefccda3",
    "shortSha": "643cb63",
    "dateIso": "2026-05-02T11:38:39+07:00",
    "author": "Bank",
    "subject": "fix(er-diagram): preventDefault on pointerdown stops text-selection hijack",
    "parents": "c4ad72089dc6b8e7eca9ad061730b6c7a7cbc025",
    "type": "fix",
    "scope": "er-diagram"
  },
  {
    "sha": "c4ad72089dc6b8e7eca9ad061730b6c7a7cbc025",
    "shortSha": "c4ad720",
    "dateIso": "2026-05-02T11:24:10+07:00",
    "author": "Bank",
    "subject": "fix(admin/timeline): single vertical spine instead of broken fishbone",
    "parents": "28940a28a576002d71eb20b174a9e2546c8bab60",
    "type": "fix",
    "scope": "admin/timeline"
  },
  {
    "sha": "28940a28a576002d71eb20b174a9e2546c8bab60",
    "shortSha": "28940a2",
    "dateIso": "2026-05-02T11:15:51+07:00",
    "author": "Bank",
    "subject": "feat(admin): commit timeline page + remove old cleanup scripts",
    "parents": "38c25838d7339fa3109bd6b76923ade07141f955",
    "type": "feat",
    "scope": "admin"
  },
  {
    "sha": "38c25838d7339fa3109bd6b76923ade07141f955",
    "shortSha": "38c2583",
    "dateIso": "2026-05-02T11:11:05+07:00",
    "author": "Bank",
    "subject": "tools: remove sanitize-and-cleanup.py",
    "parents": "121f4d3db098976b1761148fcbc397ea9c68dbe2",
    "type": "tools",
    "scope": null
  },
  {
    "sha": "121f4d3db098976b1761148fcbc397ea9c68dbe2",
    "shortSha": "121f4d3",
    "dateIso": "2026-05-02T10:51:27+07:00",
    "author": "Bank",
    "subject": "tools: one-shot script to scrub personal emails + trim long commit bodies",
    "parents": "b3b2c8a7ad9af86e09664e29f954cef5938d01a1",
    "type": "tools",
    "scope": null
  },
  {
    "sha": "b3b2c8a7ad9af86e09664e29f954cef5938d01a1",
    "shortSha": "b3b2c8a",
    "dateIso": "2026-05-02T10:45:50+07:00",
    "author": "Bank",
    "subject": "docs: remove personal emails from live-stores section",
    "parents": "4bfa0d5f54e775a664ac20b0993328d76b46eada",
    "type": "docs",
    "scope": null
  },
  {
    "sha": "4bfa0d5f54e775a664ac20b0993328d76b46eada",
    "shortSha": "4bfa0d5",
    "dateIso": "2026-05-02T10:44:40+07:00",
    "author": "Bank",
    "subject": "docs: trim README — less marketing, fix the seed-store note",
    "parents": "905ff7743fce793cb26d89e91ae90365608270c9",
    "type": "docs",
    "scope": null
  },
  {
    "sha": "905ff7743fce793cb26d89e91ae90365608270c9",
    "shortSha": "905ff77",
    "dateIso": "2026-05-02T10:38:16+07:00",
    "author": "Bank",
    "subject": "docs(phase-47): ER diagram fullscreen + drag-from-anywhere, changelog + README updates",
    "parents": "d46b226feb3e87a805ed8e01aa6945c0e2298f3f",
    "type": "docs",
    "scope": "phase-47"
  },
  {
    "sha": "d46b226feb3e87a805ed8e01aa6945c0e2298f3f",
    "shortSha": "d46b226",
    "dateIso": "2026-05-02T10:11:23+07:00",
    "author": "Bank",
    "subject": "fix(topnav): match category order + labels with /browse left sidebar",
    "parents": "f066737c95e0e92728e86d89e40f329bf77b63b4",
    "type": "fix",
    "scope": "topnav"
  },
  {
    "sha": "f066737c95e0e92728e86d89e40f329bf77b63b4",
    "shortSha": "f066737",
    "dateIso": "2026-05-02T09:38:44+07:00",
    "author": "Bank",
    "subject": "fix(topnav): category chips now point at real DB category IDs",
    "parents": "a9f6b21cc74c46bde069fb750556537b5581b7ed",
    "type": "fix",
    "scope": "topnav"
  },
  {
    "sha": "a9f6b21cc74c46bde069fb750556537b5581b7ed",
    "shortSha": "a9f6b21",
    "dateIso": "2026-05-02T09:28:20+07:00",
    "author": "Bank",
    "subject": "data: seed Pixel Forge Bangkok (store 5) with 30 game-dev products",
    "parents": "f242d61e810e110f22cab90e496d012d0f382d53",
    "type": "data",
    "scope": null
  },
  {
    "sha": "f242d61e810e110f22cab90e496d012d0f382d53",
    "shortSha": "f242d61",
    "dateIso": "2026-05-02T09:24:19+07:00",
    "author": "Bank",
    "subject": "fix(seller): banner now self-fetches Stripe status, no longer stale after onboarding",
    "parents": "184218878695ff4f0e46a32ac09ccf9d7b4ef4d8",
    "type": "fix",
    "scope": "seller"
  },
  {
    "sha": "184218878695ff4f0e46a32ac09ccf9d7b4ef4d8",
    "shortSha": "1842188",
    "dateIso": "2026-05-02T09:16:25+07:00",
    "author": "Bank",
    "subject": "feat(skeletons): add loading.tsx to 25 missing pages (admin, seller, others)",
    "parents": "cf321d1c11333761e872cf7dd6a40426eba83720",
    "type": "feat",
    "scope": "skeletons"
  },
  {
    "sha": "cf321d1c11333761e872cf7dd6a40426eba83720",
    "shortSha": "cf321d1",
    "dateIso": "2026-05-02T01:28:43+07:00",
    "author": "Bank",
    "subject": "fix(checkout) + feat(phase-46): Stripe Connect Element scope + Firebase Phone Auth groundwork",
    "parents": "182a730cafb3db14ca0c2a3e178ad1b94cc5d520",
    "type": "other",
    "scope": null
  },
  {
    "sha": "182a730cafb3db14ca0c2a3e178ad1b94cc5d520",
    "shortSha": "182a730",
    "dateIso": "2026-05-02T01:16:58+07:00",
    "author": "Bank",
    "subject": "fix(bff): force cache: no-store on every BFF→API fetch",
    "parents": "1ef6e8f93f29bebbe007865726557b41848d5268",
    "type": "fix",
    "scope": "bff"
  },
  {
    "sha": "1ef6e8f93f29bebbe007865726557b41848d5268",
    "shortSha": "1ef6e8f",
    "dateIso": "2026-05-01T23:11:39+07:00",
    "author": "Bank",
    "subject": "fix(admin/profile): dropdown flip-up + cache-bust reload + Google password banner",
    "parents": "3b15b05cd848c4c8a8969e512713bd233c738f3f",
    "type": "fix",
    "scope": "admin/profile"
  },
  {
    "sha": "3b15b05cd848c4c8a8969e512713bd233c738f3f",
    "shortSha": "3b15b05",
    "dateIso": "2026-05-01T23:07:04+07:00",
    "author": "Bank",
    "subject": "fix(admin): centre Confirm dialog + drop stale store row on /admin/users",
    "parents": "030f5460cedf5e304586bf8872d0e6affcbcaaa8",
    "type": "fix",
    "scope": "admin"
  },
  {
    "sha": "030f5460cedf5e304586bf8872d0e6affcbcaaa8",
    "shortSha": "030f546",
    "dateIso": "2026-05-01T23:00:51+07:00",
    "author": "Bank",
    "subject": "feat(phase-45): align schema with submitted CPE241 docx report + fix cart bugs",
    "parents": "c6113b76ab99f9f21e6f294644ca9bdccd2e5527",
    "type": "feat",
    "scope": "phase-45"
  },
  {
    "sha": "c6113b76ab99f9f21e6f294644ca9bdccd2e5527",
    "shortSha": "c6113b7",
    "dateIso": "2026-05-01T22:24:11+07:00",
    "author": "Bank",
    "subject": "fix(seller): hide \"Connect Stripe\" banner on /seller/onboarding",
    "parents": "f01818086f5acb5cc9b9cd1e006eaeead7a87d14",
    "type": "fix",
    "scope": "seller"
  },
  {
    "sha": "f01818086f5acb5cc9b9cd1e006eaeead7a87d14",
    "shortSha": "f018180",
    "dateIso": "2026-05-01T22:15:46+07:00",
    "author": "Bank",
    "subject": "fix(register): TH phone field forces 9 digits, no leading 0",
    "parents": "90edb860f481944d695566d5f1934638f6355249",
    "type": "fix",
    "scope": "register"
  },
  {
    "sha": "90edb860f481944d695566d5f1934638f6355249",
    "shortSha": "90edb86",
    "dateIso": "2026-05-01T21:48:18+07:00",
    "author": "Bank",
    "subject": "fix(seller): /seller/stripe/status returns configured:true so onboarding page renders correctly",
    "parents": "dcfa6f9d21c48673bf9fb9daf70a2c4a0823db50",
    "type": "fix",
    "scope": "seller"
  },
  {
    "sha": "dcfa6f9d21c48673bf9fb9daf70a2c4a0823db50",
    "shortSha": "dcfa6f9",
    "dateIso": "2026-05-01T21:35:04+07:00",
    "author": "Bank",
    "subject": "fix(qa): cart line images load eagerly so 80x80 thumbnails actually paint",
    "parents": "e9ad8d939ac070b9f4b7a25f756e23387b0ff495",
    "type": "fix",
    "scope": "qa"
  },
  {
    "sha": "e9ad8d939ac070b9f4b7a25f756e23387b0ff495",
    "shortSha": "e9ad8d9",
    "dateIso": "2026-05-01T21:26:17+07:00",
    "author": "Bank",
    "subject": "fix(qa): tech-stack logo lazy-load, cart line/qty label, Google new-user verify-phone bounce",
    "parents": "58390a5e87d4a10422c89bd87f48c8816024946f",
    "type": "fix",
    "scope": "qa"
  },
  {
    "sha": "58390a5e87d4a10422c89bd87f48c8816024946f",
    "shortSha": "58390a5",
    "dateIso": "2026-05-01T20:57:21+07:00",
    "author": "Bank",
    "subject": "fix(oauth): mirror userId-id on user create+update so OAuth account create gets a userId",
    "parents": "951f3e4909d609aa7e017679ae0f7ed00992b210",
    "type": "fix",
    "scope": "oauth"
  },
  {
    "sha": "951f3e4909d609aa7e017679ae0f7ed00992b210",
    "shortSha": "951f3e4",
    "dateIso": "2026-05-01T20:26:37+07:00",
    "author": "Bank",
    "subject": "fix(oauth): declare additionalFields so Google sign-in can create users",
    "parents": "5ef3309afe31f8c2086f3ba5b098dfc641fceeb1",
    "type": "fix",
    "scope": "oauth"
  },
  {
    "sha": "5ef3309afe31f8c2086f3ba5b098dfc641fceeb1",
    "shortSha": "5ef3309",
    "dateIso": "2026-05-01T20:16:00+07:00",
    "author": "Bank",
    "subject": "fix: /browse fallback when no store is Stripe-ready + register controller forwards demo payload",
    "parents": "507f54fd0cc33f1338faf1b308732a2856204216",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "507f54fd0cc33f1338faf1b308732a2856204216",
    "shortSha": "507f54f",
    "dateIso": "2026-05-01T20:05:23+07:00",
    "author": "Bank",
    "subject": "fix(phase-43): defense round-2 bug sweep",
    "parents": "40887320a82573b87208ff5b8dc7ae343d300d81",
    "type": "fix",
    "scope": "phase-43"
  },
  {
    "sha": "40887320a82573b87208ff5b8dc7ae343d300d81",
    "shortSha": "4088732",
    "dateIso": "2026-05-01T19:00:55+07:00",
    "author": "Bank",
    "subject": "feat: tech-stack flowchart with brand logos + Phase 41/42 changelog",
    "parents": "b2357f53dad208e06a1afc15607da9d54fe40851",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "b2357f53dad208e06a1afc15607da9d54fe40851",
    "shortSha": "b2357f5",
    "dateIso": "2026-05-01T18:55:35+07:00",
    "author": "Bank",
    "subject": "fix(admin): dialog wraps long bodies, stores show Suspended/Deleted badges, busy state resets",
    "parents": "0280ba97b1e368ed82a68dfb0fae9da65c23ab0a",
    "type": "fix",
    "scope": "admin"
  },
  {
    "sha": "0280ba97b1e368ed82a68dfb0fae9da65c23ab0a",
    "shortSha": "0280ba9",
    "dateIso": "2026-05-01T18:51:02+07:00",
    "author": "Bank",
    "subject": "fix(oauth): strip Domain= when mirroring API Set-Cookie + better error messages",
    "parents": "f52444daf943027c2825d991133aec10cfd39a97",
    "type": "fix",
    "scope": "oauth"
  },
  {
    "sha": "f52444daf943027c2825d991133aec10cfd39a97",
    "shortSha": "f52444d",
    "dateIso": "2026-05-01T18:04:30+07:00",
    "author": "Bank",
    "subject": "feat: show free-sample preview link to store owner on own products",
    "parents": "569852bebf7f3f19895c135a6d84b7a0340f59e3",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "569852bebf7f3f19895c135a6d84b7a0340f59e3",
    "shortSha": "569852b",
    "dateIso": "2026-05-01T17:57:25+07:00",
    "author": "Bank",
    "subject": "feat: phase 42 batch 2 — Google account linking, shared sign-in button, country phone picker",
    "parents": "9ae0b4ee4897d9e860eebeed1ee67cd92e03f0d7",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "9ae0b4ee4897d9e860eebeed1ee67cd92e03f0d7",
    "shortSha": "9ae0b4e",
    "dateIso": "2026-05-01T17:44:59+07:00",
    "author": "Bank",
    "subject": "feat: phase 42 batch — own-store guard, stripe-ready filter, delivery URLs, plain-English errors, URL hardening",
    "parents": "3a9df2f13e34019688fff1a431e914cce90d712d",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "3a9df2f13e34019688fff1a431e914cce90d712d",
    "shortSha": "3a9df2f",
    "dateIso": "2026-05-01T16:09:30+07:00",
    "author": "Bank",
    "subject": "feat: rewrite /feature-tour ให้คนทั่วไปอ่านเข้าใจ ไม่ใช้ศัพท์โปรแกรมเมอร์",
    "parents": "11d6106aef2a49f1b3ce48da9fc88e7b828f1d0e",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "11d6106aef2a49f1b3ce48da9fc88e7b828f1d0e",
    "shortSha": "11d6106",
    "dateIso": "2026-05-01T16:02:33+07:00",
    "author": "Bank",
    "subject": "feat: embed ER diagram on /feature-tour + แปลเป็น english",
    "parents": "74c0f2c2037c498ac66639fa0b2be2202390f33f",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "74c0f2c2037c498ac66639fa0b2be2202390f33f",
    "shortSha": "74c0f2c",
    "dateIso": "2026-05-01T11:22:47+07:00",
    "author": "Bank",
    "subject": "fix: ห้าม cache หน้า /reset-password กันเปิดแท็บค้างหลัง token หมดอายุ",
    "parents": "32d7803fd6849a866e6f5c4929be0ed264d9568e",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "32d7803fd6849a866e6f5c4929be0ed264d9568e",
    "shortSha": "32d7803",
    "dateIso": "2026-05-01T10:42:40+07:00",
    "author": "Bank",
    "subject": "feat(phase-41): mandatory email + phone verify ตอน register",
    "parents": "f2e31274477cf5dbb5f66dc253cbfd521a87130b",
    "type": "feat",
    "scope": "phase-41"
  },
  {
    "sha": "f2e31274477cf5dbb5f66dc253cbfd521a87130b",
    "shortSha": "f2e3127",
    "dateIso": "2026-05-01T10:22:57+07:00",
    "author": "Bank",
    "subject": "chore: trim AI-style code comments + fix email logo M mark",
    "parents": "abfb80536f54d446c6c042e5daaa68f824d46450",
    "type": "chore",
    "scope": null
  },
  {
    "sha": "abfb80536f54d446c6c042e5daaa68f824d46450",
    "shortSha": "abfb805",
    "dateIso": "2026-05-01T09:55:34+07:00",
    "author": "Bank",
    "subject": "feat: branded email layout + reset link หมดอายุใน 5 นาที",
    "parents": "7f8c4f0791082b0bbfde578b1187c7cfbcaf8285",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "7f8c4f0791082b0bbfde578b1187c7cfbcaf8285",
    "shortSha": "7f8c4f0",
    "dateIso": "2026-05-01T09:36:11+07:00",
    "author": "Bank",
    "subject": "fix: BFF forward Origin header แก้ better-auth 403 MISSING_OR_NULL_ORIGIN ตอน Google login",
    "parents": "cbd6187c9ac5a53d15c9d9dd80ef90fb6cf91fdb",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "cbd6187c9ac5a53d15c9d9dd80ef90fb6cf91fdb",
    "shortSha": "cbd6187",
    "dateIso": "2026-05-01T09:29:11+07:00",
    "author": "Bank",
    "subject": "fix: เปลี่ยน flag en เป็น US (stars+stripes)",
    "parents": "2d36d1d5e7dd125ff75771bcbab796883dbedff3",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "2d36d1d5e7dd125ff75771bcbab796883dbedff3",
    "shortSha": "2d36d1d",
    "dateIso": "2026-05-01T09:28:51+07:00",
    "author": "Bank",
    "subject": "fix: เปลี่ยน flag en เป็น US (stars+stripes) + ลบ /features หน้าเก่า",
    "parents": "6978bb7674c945f83e6d4a6d3371cf532ea6c9f2",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "6978bb7674c945f83e6d4a6d3371cf532ea6c9f2",
    "shortSha": "6978bb7",
    "dateIso": "2026-05-01T09:20:07+07:00",
    "author": "Bank",
    "subject": "fix: ตัด demo wording + flag SVG + ปรับ footer feature tour link",
    "parents": "9dc544b0a26feba9bdbfe34f71f1284cacfaec17",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "9dc544b0a26feba9bdbfe34f71f1284cacfaec17",
    "shortSha": "9dc544b",
    "dateIso": "2026-05-01T09:14:36+07:00",
    "author": "Bank",
    "subject": "chore: รื้อ /admin/changelog ให้อ่านเหมือนคนเขียน, ทุก subtitle 1 ประโยค + items 1 บรรทัด",
    "parents": "70ec2117c741f946c2539e6fb6797680d37dd3b7",
    "type": "chore",
    "scope": null
  },
  {
    "sha": "70ec2117c741f946c2539e6fb6797680d37dd3b7",
    "shortSha": "70ec211",
    "dateIso": "2026-05-01T09:08:54+07:00",
    "author": "Bank",
    "subject": "feat: feature tour landing page สำหรับเปิดตอนพรีเซนต์",
    "parents": "cf08f49412b6f31c230a98e0c739d4bdc85a2c78",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "cf08f49412b6f31c230a98e0c739d4bdc85a2c78",
    "shortSha": "cf08f49",
    "dateIso": "2026-05-01T09:00:53+07:00",
    "author": "Bank",
    "subject": "chore: scripts สำหรับ cleanup git log (filter-repo + handcrafted overrides)",
    "parents": "25c68e894851ac8c424f412b6eb13fb1e39e278b",
    "type": "chore",
    "scope": null
  },
  {
    "sha": "25c68e894851ac8c424f412b6eb13fb1e39e278b",
    "shortSha": "25c68e8",
    "dateIso": "2026-04-30T23:18:45+07:00",
    "author": "Bank",
    "subject": "test(phase-37): buyer checkout -> license key delivery e2e",
    "parents": "a1bbb9b66be43326d4c86f9087f0d38ff672e799",
    "type": "test",
    "scope": "phase-37"
  },
  {
    "sha": "a1bbb9b66be43326d4c86f9087f0d38ff672e799",
    "shortSha": "a1bbb9b",
    "dateIso": "2026-04-30T23:11:06+07:00",
    "author": "Bank",
    "subject": "feat(phase-36): ER pan/zoom polish + tech stack infographic",
    "parents": "810b60b71b1dd9fefa6cf35bc311f3fb2a07e3b7",
    "type": "feat",
    "scope": "phase-36"
  },
  {
    "sha": "810b60b71b1dd9fefa6cf35bc311f3fb2a07e3b7",
    "shortSha": "810b60b",
    "dateIso": "2026-04-30T23:04:43+07:00",
    "author": "Bank",
    "subject": "fix(phase-33c): atomic stock decrement on checkout",
    "parents": "7b05a5221feb94ffc7f112a368aa18261735519d",
    "type": "fix",
    "scope": "phase-33c"
  },
  {
    "sha": "7b05a5221feb94ffc7f112a368aa18261735519d",
    "shortSha": "7b05a52",
    "dateIso": "2026-04-30T22:57:44+07:00",
    "author": "Bank",
    "subject": "feat(phase-33b): manual payout button on /seller/wallet",
    "parents": "6013191d66a597bfe6790697c94a4df14dc3de12",
    "type": "feat",
    "scope": "phase-33b"
  },
  {
    "sha": "6013191d66a597bfe6790697c94a4df14dc3de12",
    "shortSha": "6013191",
    "dateIso": "2026-04-30T22:54:49+07:00",
    "author": "Bank",
    "subject": "feat(phase-35): wire TOTP step-up modal on refund + revoke-all",
    "parents": "c7381864045c4ed1f4c3128dba37b2ecc4b58a31",
    "type": "feat",
    "scope": "phase-35"
  },
  {
    "sha": "c7381864045c4ed1f4c3128dba37b2ecc4b58a31",
    "shortSha": "c738186",
    "dateIso": "2026-04-30T22:47:28+07:00",
    "author": "Bank",
    "subject": "feat(phase-38c): master coupons (platform-wide promo codes)",
    "parents": "548ce72661e26900efacdcac58f867355a633ac1",
    "type": "feat",
    "scope": "phase-38c"
  },
  {
    "sha": "548ce72661e26900efacdcac58f867355a633ac1",
    "shortSha": "548ce72",
    "dateIso": "2026-04-30T22:43:24+07:00",
    "author": "Bank",
    "subject": "feat(phase-33): order delivery + receipt email",
    "parents": "d54b57001334bb2e9d6e1fb9f4bafff3cb24af37",
    "type": "feat",
    "scope": "phase-33"
  },
  {
    "sha": "d54b57001334bb2e9d6e1fb9f4bafff3cb24af37",
    "shortSha": "d54b570",
    "dateIso": "2026-04-30T22:33:54+07:00",
    "author": "Bank",
    "subject": "fix(phase-38): tier-1 prep sweep before defense",
    "parents": "ffe005c002d0e81ff6e73c7563bd5129c94c5eb3",
    "type": "fix",
    "scope": "phase-38"
  },
  {
    "sha": "ffe005c002d0e81ff6e73c7563bd5129c94c5eb3",
    "shortSha": "ffe005c",
    "dateIso": "2026-04-30T21:20:31+07:00",
    "author": "Bank",
    "subject": "feat(phase-22): security headers on the BFF + explicit cookie attrs",
    "parents": "5c3d0212b6a6f5997656799512067cab6760e8f7",
    "type": "feat",
    "scope": "phase-22"
  },
  {
    "sha": "5c3d0212b6a6f5997656799512067cab6760e8f7",
    "shortSha": "5c3d021",
    "dateIso": "2026-04-30T18:48:32+07:00",
    "author": "Bank",
    "subject": "feat(phase-32): TH-compliant Stripe Connect (recipient model + seed script)",
    "parents": "30ae03d78c578444672763e1c4cd529efa636374",
    "type": "feat",
    "scope": "phase-32"
  },
  {
    "sha": "30ae03d78c578444672763e1c4cd529efa636374",
    "shortSha": "30ae03d",
    "dateIso": "2026-04-30T17:51:33+07:00",
    "author": "Bank",
    "subject": "fix(phase-31): Google login click + add-to-cart Prisma error + Stripe onboarding nudge",
    "parents": "e93500ad8ca4c8f51cfd03c0c0307e26d1fe9c79",
    "type": "fix",
    "scope": "phase-31"
  },
  {
    "sha": "e93500ad8ca4c8f51cfd03c0c0307e26d1fe9c79",
    "shortSha": "e93500a",
    "dateIso": "2026-04-30T17:29:15+07:00",
    "author": "Bank",
    "subject": "fix(phase-31): seller pages — use apiFetch with cookie forwarding",
    "parents": "bb3f1bfb0636c7d6b0f597045979665ce5fe162e",
    "type": "fix",
    "scope": "phase-31"
  },
  {
    "sha": "bb3f1bfb0636c7d6b0f597045979665ce5fe162e",
    "shortSha": "bb3f1bf",
    "dateIso": "2026-04-30T16:35:44+07:00",
    "author": "Bank",
    "subject": "fix(phase-27): switch to Platform model (direct charge) for Thailand",
    "parents": "c9309354b035b8fc41a766580ee0eec39a17c4b1",
    "type": "fix",
    "scope": "phase-27"
  },
  {
    "sha": "c9309354b035b8fc41a766580ee0eec39a17c4b1",
    "shortSha": "c930935",
    "dateIso": "2026-04-30T13:57:55+07:00",
    "author": "Bank",
    "subject": "docs(phase-32): docx v4 scope — full prospective scope document",
    "parents": "631155f30bffe99936efff611dbee868ada1855e",
    "type": "docs",
    "scope": "phase-32"
  },
  {
    "sha": "631155f30bffe99936efff611dbee868ada1855e",
    "shortSha": "631155f",
    "dateIso": "2026-04-30T13:35:34+07:00",
    "author": "Bank",
    "subject": "fix(phase-31): widen simple-bend threshold to Δcol ≤ 4",
    "parents": "410addf4364c12b10078480e0961cdacdbe4585f",
    "type": "fix",
    "scope": "phase-31"
  },
  {
    "sha": "410addf4364c12b10078480e0961cdacdbe4585f",
    "shortSha": "410addf",
    "dateIso": "2026-04-30T13:27:29+07:00",
    "author": "Bank",
    "subject": "fix(phase-31): ER diagram routing — highway routes for non-adjacent edges",
    "parents": "2dd9c3171fa92807f3a88cb15c73a80a4004539e",
    "type": "fix",
    "scope": "phase-31"
  },
  {
    "sha": "2dd9c3171fa92807f3a88cb15c73a80a4004539e",
    "shortSha": "2dd9c31",
    "dateIso": "2026-04-30T13:02:28+07:00",
    "author": "Bank",
    "subject": "docs(phase-29): regenerate ER diagram + ship CPE 241 Database v3.docx",
    "parents": "8716918d3f15be8b9d6b205b1a864ee8802cb67d",
    "type": "docs",
    "scope": "phase-29"
  },
  {
    "sha": "8716918d3f15be8b9d6b205b1a864ee8802cb67d",
    "shortSha": "8716918",
    "dateIso": "2026-04-30T10:02:32+07:00",
    "author": "Bank",
    "subject": "chore(phase-28): migrate database from Neon to Supabase",
    "parents": "1a09cb620f11d4caf982b7653776d6c339d7c02e",
    "type": "chore",
    "scope": "phase-28"
  },
  {
    "sha": "1a09cb620f11d4caf982b7653776d6c339d7c02e",
    "shortSha": "1a09cb6",
    "dateIso": "2026-04-30T09:33:15+07:00",
    "author": "Bank",
    "subject": "feat(phase-27): Stripe Connect (test mode) replaces PromptPay",
    "parents": "4dcc4d24bd54d921063ab31140dc2923977319ce",
    "type": "feat",
    "scope": "phase-27"
  },
  {
    "sha": "4dcc4d24bd54d921063ab31140dc2923977319ce",
    "shortSha": "4dcc4d2",
    "dateIso": "2026-04-30T02:44:38+07:00",
    "author": "Bank",
    "subject": "feat(phase-26): trim messaging, q&a, stock alerts, and PromptPay wallet system",
    "parents": "cc28280e1fc19a14c34d35a6d154afb31c56f45a",
    "type": "feat",
    "scope": "phase-26"
  },
  {
    "sha": "cc28280e1fc19a14c34d35a6d154afb31c56f45a",
    "shortSha": "cc28280",
    "dateIso": "2026-04-30T02:21:50+07:00",
    "author": "Bank",
    "subject": "chore(phase-25): docx extend helper script",
    "parents": "46d3bf57eba663f91b3856eebe56eca606cf8026",
    "type": "chore",
    "scope": "phase-25"
  },
  {
    "sha": "46d3bf57eba663f91b3856eebe56eca606cf8026",
    "shortSha": "46d3bf5",
    "dateIso": "2026-04-30T00:04:42+07:00",
    "author": "Bank",
    "subject": "Delete ER_REVIEW.html",
    "parents": "08d7548193248609187bcc7ce41294e2b28719fb",
    "type": "other",
    "scope": null
  },
  {
    "sha": "08d7548193248609187bcc7ce41294e2b28719fb",
    "shortSha": "08d7548",
    "dateIso": "2026-04-30T00:04:31+07:00",
    "author": "Bank",
    "subject": "Delete BRIEF.html",
    "parents": "5dd75aef0e2dd761e856a27414c8702bec06bdff",
    "type": "other",
    "scope": null
  },
  {
    "sha": "5dd75aef0e2dd761e856a27414c8702bec06bdff",
    "shortSha": "5dd75ae",
    "dateIso": "2026-04-29T23:44:05+07:00",
    "author": "Bank",
    "subject": "fix(phase-24): snap edge bends to inter-column gaps",
    "parents": "0293f42323c65d8ba9426fc088a9321467d53b80",
    "type": "fix",
    "scope": "phase-24"
  },
  {
    "sha": "0293f42323c65d8ba9426fc088a9321467d53b80",
    "shortSha": "0293f42",
    "dateIso": "2026-04-29T23:28:06+07:00",
    "author": "Bank",
    "subject": "fix(phase-24): category-grid layout for ER diagram",
    "parents": "d7c98e50a3eab7315458e5c05f3867667c11e331",
    "type": "fix",
    "scope": "phase-24"
  },
  {
    "sha": "d7c98e50a3eab7315458e5c05f3867667c11e331",
    "shortSha": "d7c98e5",
    "dateIso": "2026-04-29T22:51:26+07:00",
    "author": "Bank848",
    "subject": "fix(phase-24): SVG/PNG export markers + pure-SVG cards + spacing",
    "parents": "33b03523df12dffc37717e234f7e9daea161d596",
    "type": "fix",
    "scope": "phase-24"
  },
  {
    "sha": "33b03523df12dffc37717e234f7e9daea161d596",
    "shortSha": "33b0352",
    "dateIso": "2026-04-29T22:11:23+07:00",
    "author": "Bank848",
    "subject": "feat(phase-24): in-house ER diagram — drops Lucidchart embed",
    "parents": "a5aad3dd885d29352a2ddf72d8b4da8b6347522a",
    "type": "feat",
    "scope": "phase-24"
  },
  {
    "sha": "a5aad3dd885d29352a2ddf72d8b4da8b6347522a",
    "shortSha": "a5aad3d",
    "dateIso": "2026-04-29T22:10:26+07:00",
    "author": "Bank848",
    "subject": "feat(phase-23.3): TOTP step-up on sensitive actions",
    "parents": "c493b6216bd5d0cda1349e4039f4b1554532becc",
    "type": "feat",
    "scope": "phase-23.3"
  },
  {
    "sha": "c493b6216bd5d0cda1349e4039f4b1554532becc",
    "shortSha": "c493b62",
    "dateIso": "2026-04-29T17:36:37+07:00",
    "author": "Bank848",
    "subject": "feat(phase-23.1+23.2): sessions UI page + audit log gap fills",
    "parents": "b5815d11f8412f45e257448d8f27ce8a9dceaac4",
    "type": "feat",
    "scope": "phase-23.1+23.2"
  },
  {
    "sha": "b5815d11f8412f45e257448d8f27ce8a9dceaac4",
    "shortSha": "b5815d1",
    "dateIso": "2026-04-29T17:35:24+07:00",
    "author": "Bank848",
    "subject": "fix(phase-20.2): correct withdrawal FK reference users(user_id)",
    "parents": "b9a3fbe6452386fc21031d9d63949168aa322f08",
    "type": "fix",
    "scope": "phase-20.2"
  },
  {
    "sha": "b9a3fbe6452386fc21031d9d63949168aa322f08",
    "shortSha": "b9a3fbe",
    "dateIso": "2026-04-29T17:07:41+07:00",
    "author": "Bank848",
    "subject": "feat(phase-22): security hardening — helmet/CSP, rate-limits, profanity",
    "parents": "d2ed29d42a8307dd361d7170ab8eb4b60e25f861",
    "type": "feat",
    "scope": "phase-22"
  },
  {
    "sha": "d2ed29d42a8307dd361d7170ab8eb4b60e25f861",
    "shortSha": "d2ed29d",
    "dateIso": "2026-04-29T16:52:10+07:00",
    "author": "Bank848",
    "subject": "feat(phase-20.2): seller withdrawal — request flow + admin queue",
    "parents": "487c1c077b5cadb5646c171e3f4c1ef23f43a1e5",
    "type": "feat",
    "scope": "phase-20.2"
  },
  {
    "sha": "487c1c077b5cadb5646c171e3f4c1ef23f43a1e5",
    "shortSha": "487c1c0",
    "dateIso": "2026-04-29T16:37:08+07:00",
    "author": "Bank848",
    "subject": "feat(phase-20.1): wire wallet ledger into checkout + platform fee",
    "parents": "f3f08dd685b5bf46e91cd699a37c29f38a47f6e1",
    "type": "feat",
    "scope": "phase-20.1"
  },
  {
    "sha": "f3f08dd685b5bf46e91cd699a37c29f38a47f6e1",
    "shortSha": "f3f08dd",
    "dateIso": "2026-04-29T16:29:51+07:00",
    "author": "Bank848",
    "subject": "feat(phase-21): admin docs pages — Lucidchart ER + tech stack",
    "parents": "c32b91e281486c31ab84aa8fabce57d0cf8ddd43",
    "type": "feat",
    "scope": "phase-21"
  },
  {
    "sha": "c32b91e281486c31ab84aa8fabce57d0cf8ddd43",
    "shortSha": "c32b91e",
    "dateIso": "2026-04-29T16:19:08+07:00",
    "author": "Bank848",
    "subject": "feat(phase-19): chatEnabled surface gating — mirrors favorites pattern",
    "parents": "bf6f4f3169cab51d56bc6141404c8c7bf022c501",
    "type": "feat",
    "scope": "phase-19"
  },
  {
    "sha": "bf6f4f3169cab51d56bc6141404c8c7bf022c501",
    "shortSha": "bf6f4f3",
    "dateIso": "2026-04-29T16:08:16+07:00",
    "author": "Bank848",
    "subject": "feat(phase-18): google login finalization — env docs + ConnectedAccounts UI",
    "parents": "98403c20da36688df56cbfe1076cf04d29499bba",
    "type": "feat",
    "scope": "phase-18"
  },
  {
    "sha": "98403c20da36688df56cbfe1076cf04d29499bba",
    "shortSha": "98403c2",
    "dateIso": "2026-04-29T11:52:22+07:00",
    "author": "Bank",
    "subject": "feat(phase-17.3): PromptPay top-up flow — user UI + admin queue",
    "parents": "4cae7221b86961af00efcc611a2bb8526cff230b",
    "type": "feat",
    "scope": "phase-17.3"
  },
  {
    "sha": "4cae7221b86961af00efcc611a2bb8526cff230b",
    "shortSha": "4cae722",
    "dateIso": "2026-04-29T11:39:50+07:00",
    "author": "Bank",
    "subject": "feat(phase-17.x): favoritesEnabled flag + admin toggle + surface gating",
    "parents": "49d92d2625b755915f9ccde94b99b61aeed18b0f",
    "type": "feat",
    "scope": "phase-17.x"
  },
  {
    "sha": "49d92d2625b755915f9ccde94b99b61aeed18b0f",
    "shortSha": "49d92d2",
    "dateIso": "2026-04-29T11:28:23+07:00",
    "author": "Bank",
    "subject": "fix(phase-17.x): hide Google button when API doesn't have OAuth creds",
    "parents": "9ec0d8005760da4c54b431507266b1ea4fc3725c",
    "type": "fix",
    "scope": "phase-17.x"
  },
  {
    "sha": "9ec0d8005760da4c54b431507266b1ea4fc3725c",
    "shortSha": "9ec0d80",
    "dateIso": "2026-04-29T11:19:20+07:00",
    "author": "Bank",
    "subject": "feat(phase-17.3.0): PromptPay deps + slip-verify util (not yet wired)",
    "parents": "ff0cd236aafc6155bb2f64b15a9cd01fc1c3c0bd",
    "type": "feat",
    "scope": "phase-17.3.0"
  },
  {
    "sha": "ff0cd236aafc6155bb2f64b15a9cd01fc1c3c0bd",
    "shortSha": "ff0cd23",
    "dateIso": "2026-04-29T11:15:39+07:00",
    "author": "Bank",
    "subject": "feat(phase-17.2): coin pricing migration — ฿ → coins everywhere",
    "parents": "9104615d06bbe89995f94a40e7319c96c411a489",
    "type": "feat",
    "scope": "phase-17.2"
  },
  {
    "sha": "9104615d06bbe89995f94a40e7319c96c411a489",
    "shortSha": "9104615",
    "dateIso": "2026-04-29T11:05:49+07:00",
    "author": "Bank",
    "subject": "feat(phase-17.1): wallet + system settings foundation",
    "parents": "5b29581206665e1325955f601c6bc1291d9f2f3d",
    "type": "feat",
    "scope": "phase-17.1"
  },
  {
    "sha": "5b29581206665e1325955f601c6bc1291d9f2f3d",
    "shortSha": "5b29581",
    "dateIso": "2026-04-29T10:21:31+07:00",
    "author": "Bank",
    "subject": "fix(changelog): document phase-16.3 post-deploy fixes (eab0b91, 050b3a9, 155da10)",
    "parents": "155da10ac2907d24cf0de0e5876a4d0e4f8f397e",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "155da10ac2907d24cf0de0e5876a4d0e4f8f397e",
    "shortSha": "155da10",
    "dateIso": "2026-04-29T10:12:40+07:00",
    "author": "Bank",
    "subject": "fix(phase-16.3): proxy also rewrites id→userId in WHERE clauses",
    "parents": "050b3a9c1720247a62997a05afebb3bfe6017b74",
    "type": "fix",
    "scope": "phase-16.3"
  },
  {
    "sha": "050b3a9c1720247a62997a05afebb3bfe6017b74",
    "shortSha": "050b3a9",
    "dateIso": "2026-04-29T10:06:39+07:00",
    "author": "Bank",
    "subject": "fix(phase-16.3): mirror userId→id on Prisma user reads (real root cause)",
    "parents": "eab0b91282020397d4f92fb3c7748e4c569901ae",
    "type": "fix",
    "scope": "phase-16.3"
  },
  {
    "sha": "eab0b91282020397d4f92fb3c7748e4c569901ae",
    "shortSha": "eab0b91",
    "dateIso": "2026-04-29T09:47:33+07:00",
    "author": "Bank",
    "subject": "fix(phase-16.3): User.updatedAt + createdAt field mapping (root-cause prod login bug)",
    "parents": "e5ff08504ed34cf5f6ffa8f8002e75f48e1789e9",
    "type": "fix",
    "scope": "phase-16.3"
  },
  {
    "sha": "e5ff08504ed34cf5f6ffa8f8002e75f48e1789e9",
    "shortSha": "e5ff085",
    "dateIso": "2026-04-29T08:57:44+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA f0a89b7 for phase-16-3 commit link",
    "parents": "f0a89b754667bf61bdce14a790c2f695fb0ee639",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "f0a89b754667bf61bdce14a790c2f695fb0ee639",
    "shortSha": "f0a89b7",
    "dateIso": "2026-04-29T08:57:21+07:00",
    "author": "Bank",
    "subject": "feat(phase-16.3): frontend rebuild + retry migration + drop dead BFF auth helpers",
    "parents": "33a5003680639773c763235dd548cd4083f27641",
    "type": "feat",
    "scope": "phase-16.3"
  },
  {
    "sha": "33a5003680639773c763235dd548cd4083f27641",
    "shortSha": "33a5003",
    "dateIso": "2026-04-29T08:44:53+07:00",
    "author": "Bank",
    "subject": "fix(phase-16.3): migration uses created_date (legacy users table column)",
    "parents": "2a8bd21e677da79b0fc7883f3b22d601b7a106c7",
    "type": "fix",
    "scope": "phase-16.3"
  },
  {
    "sha": "2a8bd21e677da79b0fc7883f3b22d601b7a106c7",
    "shortSha": "2a8bd21",
    "dateIso": "2026-04-29T08:39:13+07:00",
    "author": "Bank",
    "subject": "feat(phase-16.3): backend Mode A swap — better-auth owns the cookie",
    "parents": "f6a9ea93f8b11aee70807037c747a511663847d2",
    "type": "feat",
    "scope": "phase-16.3"
  },
  {
    "sha": "f6a9ea93f8b11aee70807037c747a511663847d2",
    "shortSha": "f6a9ea9",
    "dateIso": "2026-04-29T05:56:12+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA dc81574 for phase-16-2 commit link",
    "parents": "dc81574809a50a2aca1ea48c00460ab8e4c12098",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "dc81574809a50a2aca1ea48c00460ab8e4c12098",
    "shortSha": "dc81574",
    "dateIso": "2026-04-29T05:55:45+07:00",
    "author": "Bank",
    "subject": "feat(phase-16.2): TOTP 2FA — authenticator-app two-factor sign-in",
    "parents": "81374f4ce74b28e700842e5786ef021bedb0bc87",
    "type": "feat",
    "scope": "phase-16.2"
  },
  {
    "sha": "81374f4ce74b28e700842e5786ef021bedb0bc87",
    "shortSha": "81374f4",
    "dateIso": "2026-04-29T05:21:20+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 1878905 for phase-16-1 commit link",
    "parents": "187890570dd696885c6853741ed0584def8199ef",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "187890570dd696885c6853741ed0584def8199ef",
    "shortSha": "1878905",
    "dateIso": "2026-04-29T05:20:50+07:00",
    "author": "Bank",
    "subject": "feat(phase-16.1): suspended stores — reversible 'freeze' alternative to delete",
    "parents": "1c5da6bdbc34f98a7efc8dda2902a969e43affee",
    "type": "feat",
    "scope": "phase-16.1"
  },
  {
    "sha": "1c5da6bdbc34f98a7efc8dda2902a969e43affee",
    "shortSha": "1c5da6b",
    "dateIso": "2026-04-29T05:04:19+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 94cad95 for phase-15-5 commit link",
    "parents": "94cad95f568d3bf36ac60f0c699ebca7688181d0",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "94cad95f568d3bf36ac60f0c699ebca7688181d0",
    "shortSha": "94cad95",
    "dateIso": "2026-04-29T05:03:53+07:00",
    "author": "Bank",
    "subject": "feat(phase-15.5): admin force-password-reset (Phase 15 complete) + Google button always visible",
    "parents": "c8e56bfda88fc59f010fcfe711c46e58392fbdd0",
    "type": "feat",
    "scope": "phase-15.5"
  },
  {
    "sha": "c8e56bfda88fc59f010fcfe711c46e58392fbdd0",
    "shortSha": "c8e56bf",
    "dateIso": "2026-04-28T23:56:50+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA baa8a08 for phase-15-3 commit link",
    "parents": "baa8a0894ecc257082e5d5df46f5cb9d7dc86bab",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "baa8a0894ecc257082e5d5df46f5cb9d7dc86bab",
    "shortSha": "baa8a08",
    "dateIso": "2026-04-28T23:56:21+07:00",
    "author": "Bank",
    "subject": "feat(phase-15.3): sensitive ops require fresh OTP when phone verified",
    "parents": "1249323ace97c5811ec5bb75d2e1a9aa8138dc25",
    "type": "feat",
    "scope": "phase-15.3"
  },
  {
    "sha": "1249323ace97c5811ec5bb75d2e1a9aa8138dc25",
    "shortSha": "1249323",
    "dateIso": "2026-04-28T23:47:51+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA ca1d07b for phase-15-4 commit link",
    "parents": "ca1d07bb03e6cbd7a46d0d40d6fcdd14c6216b22",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "ca1d07bb03e6cbd7a46d0d40d6fcdd14c6216b22",
    "shortSha": "ca1d07b",
    "dateIso": "2026-04-28T23:47:23+07:00",
    "author": "Bank",
    "subject": "feat(phase-15.4): audit log captures IP + User-Agent",
    "parents": "bbf0d62ca1b4e2025a0ac40d92ca713227081c60",
    "type": "feat",
    "scope": "phase-15.4"
  },
  {
    "sha": "bbf0d62ca1b4e2025a0ac40d92ca713227081c60",
    "shortSha": "bbf0d62",
    "dateIso": "2026-04-28T23:33:35+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 6b5f1e1 for phase-15-2 commit link",
    "parents": "6b5f1e11143d3e0d1c057face8a9c75285661c9a",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "6b5f1e11143d3e0d1c057face8a9c75285661c9a",
    "shortSha": "6b5f1e1",
    "dateIso": "2026-04-28T23:33:10+07:00",
    "author": "Bank",
    "subject": "feat(phase-15.2): active sessions UI (list + revoke + sign-out-everywhere)",
    "parents": "bb3cda5baebffc7bbf2991195f5a8751eaccdee7",
    "type": "feat",
    "scope": "phase-15.2"
  },
  {
    "sha": "bb3cda5baebffc7bbf2991195f5a8751eaccdee7",
    "shortSha": "bb3cda5",
    "dateIso": "2026-04-28T23:21:04+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 4189017 for phase-15-1 commit link",
    "parents": "4189017083dc375001ed4ac6d3ae232009f9694b",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "4189017083dc375001ed4ac6d3ae232009f9694b",
    "shortSha": "4189017",
    "dateIso": "2026-04-28T23:19:39+07:00",
    "author": "Bank",
    "subject": "feat(phase-15.1): rate-limit middleware (sliding window, in-memory)",
    "parents": "ea2e74d5d826304462f993d400d02e3744f933b1",
    "type": "feat",
    "scope": "phase-15.1"
  },
  {
    "sha": "ea2e74d5d826304462f993d400d02e3744f933b1",
    "shortSha": "ea2e74d",
    "dateIso": "2026-04-28T23:06:54+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 2a1805e for phase-14-4 commit link",
    "parents": "2a1805e5f6096f2af315a8f3b34b919c1e8a292b",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "2a1805e5f6096f2af315a8f3b34b919c1e8a292b",
    "shortSha": "2a1805e",
    "dateIso": "2026-04-28T23:06:23+07:00",
    "author": "Bank",
    "subject": "feat(phase-14.4): phone + OTP scaffold (Phase 14 complete)",
    "parents": "c493b689b0302ec8bb6a288629710ef7c48ab887",
    "type": "feat",
    "scope": "phase-14.4"
  },
  {
    "sha": "c493b689b0302ec8bb6a288629710ef7c48ab887",
    "shortSha": "c493b68",
    "dateIso": "2026-04-28T22:49:30+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 7a281f9 for phase-14-3-5 commit link",
    "parents": "7a281f94ae761d4d18f250fa2bf52ebd3771c3ea",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "7a281f94ae761d4d18f250fa2bf52ebd3771c3ea",
    "shortSha": "7a281f9",
    "dateIso": "2026-04-28T22:48:39+07:00",
    "author": "Bank",
    "subject": "feat(phase-14.3.5): linking fork — Google email collision rejected with hint",
    "parents": "78a8b8dae6b6f1deacf64d5aaeab92ba3b4ea86f",
    "type": "feat",
    "scope": "phase-14.3.5"
  },
  {
    "sha": "78a8b8dae6b6f1deacf64d5aaeab92ba3b4ea86f",
    "shortSha": "78a8b8d",
    "dateIso": "2026-04-28T21:53:38+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 0fa2c5a for phase-14-3 commit link",
    "parents": "0fa2c5af4deb5debaef5c523db7bf5883944350c",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "0fa2c5af4deb5debaef5c523db7bf5883944350c",
    "shortSha": "0fa2c5a",
    "dateIso": "2026-04-28T21:53:08+07:00",
    "author": "Bank",
    "subject": "feat(phase-14.3): set-password flow for OAuth-only users",
    "parents": "f0538f26c5a281b123deac85fdfd86e91c01ee3d",
    "type": "feat",
    "scope": "phase-14.3"
  },
  {
    "sha": "f0538f26c5a281b123deac85fdfd86e91c01ee3d",
    "shortSha": "f0538f2",
    "dateIso": "2026-04-28T21:29:59+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 60fa6d3 for phase-14-2 commit link",
    "parents": "60fa6d3c0ea62f7702069971311720caacd73420",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "60fa6d3c0ea62f7702069971311720caacd73420",
    "shortSha": "60fa6d3",
    "dateIso": "2026-04-28T21:29:02+07:00",
    "author": "Bank",
    "subject": "feat(phase-14.2): Google sign-in + dual-stack auth middleware",
    "parents": "e15b00a7115e72f2beaa28c431bd211441a7322f",
    "type": "feat",
    "scope": "phase-14.2"
  },
  {
    "sha": "e15b00a7115e72f2beaa28c431bd211441a7322f",
    "shortSha": "e15b00a",
    "dateIso": "2026-04-28T21:07:28+07:00",
    "author": "Bank",
    "subject": "fix(phase-14.1): copy workspace-local node_modules to runner stage too",
    "parents": "a4b65fbc03b2f138416d430433005460ac66befe",
    "type": "fix",
    "scope": "phase-14.1"
  },
  {
    "sha": "a4b65fbc03b2f138416d430433005460ac66befe",
    "shortSha": "a4b65fb",
    "dateIso": "2026-04-28T20:57:29+07:00",
    "author": "Bank",
    "subject": "fix(phase-14.1): copy workspace-local node_modules in server Dockerfile",
    "parents": "236fb40c8efdce4c28f2d3d75db64f0a0473da8a",
    "type": "fix",
    "scope": "phase-14.1"
  },
  {
    "sha": "236fb40c8efdce4c28f2d3d75db64f0a0473da8a",
    "shortSha": "236fb40",
    "dateIso": "2026-04-28T20:53:13+07:00",
    "author": "Bank",
    "subject": "fix(phase-14.1): import prismaAdapter from standalone package",
    "parents": "c1e59462782bd1c6e5f84db225e5630990b43a3e",
    "type": "fix",
    "scope": "phase-14.1"
  },
  {
    "sha": "c1e59462782bd1c6e5f84db225e5630990b43a3e",
    "shortSha": "c1e5946",
    "dateIso": "2026-04-28T20:45:11+07:00",
    "author": "Bank",
    "subject": "fix(phase-14.1): pin @better-auth/prisma-adapter as direct dep",
    "parents": "68d066135333d2828f5b33cee7e34321ff5a249e",
    "type": "fix",
    "scope": "phase-14.1"
  },
  {
    "sha": "68d066135333d2828f5b33cee7e34321ff5a249e",
    "shortSha": "68d0661",
    "dateIso": "2026-04-28T20:39:30+07:00",
    "author": "Bank",
    "subject": "fix(phase-14.1): drop --ignore-scripts from apps/server Dockerfile",
    "parents": "9913272f435fea483c603a95458a6323b25dc863",
    "type": "fix",
    "scope": "phase-14.1"
  },
  {
    "sha": "9913272f435fea483c603a95458a6323b25dc863",
    "shortSha": "9913272",
    "dateIso": "2026-04-28T19:20:11+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA e6617e4 for phase-14-1 commit link",
    "parents": "e6617e4c4ad1aa7008d407de2f3eb9b67246bc09",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "e6617e4c4ad1aa7008d407de2f3eb9b67246bc09",
    "shortSha": "e6617e4",
    "dateIso": "2026-04-28T19:19:15+07:00",
    "author": "Bank",
    "subject": "feat(phase-14.1): better-auth plumbing — schema + catch-all mounted",
    "parents": "14f234970ec719cfc8edd7e8406afdd65be153a8",
    "type": "feat",
    "scope": "phase-14.1"
  },
  {
    "sha": "14f234970ec719cfc8edd7e8406afdd65be153a8",
    "shortSha": "14f2349",
    "dateIso": "2026-04-28T18:42:06+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA c175fdd for phase-13-11 commit link",
    "parents": "c175fddc4d645d5a31cee41fb7df37a7108c801d",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "c175fddc4d645d5a31cee41fb7df37a7108c801d",
    "shortSha": "c175fdd",
    "dateIso": "2026-04-28T18:41:20+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.11): backend separation cleanup — last legacy routers gone",
    "parents": "ec98ef54fc42f2ba10170492e9373bbaefefccf6",
    "type": "feat",
    "scope": "phase-13.11"
  },
  {
    "sha": "ec98ef54fc42f2ba10170492e9373bbaefefccf6",
    "shortSha": "ec98ef5",
    "dateIso": "2026-04-28T18:18:50+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHA 3d4baa2 for phase-13-10 commit link",
    "parents": "3d4baa24ba9cdd6d6c619d803c6b760d9a4819fb",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "3d4baa24ba9cdd6d6c619d803c6b760d9a4819fb",
    "shortSha": "3d4baa2",
    "dateIso": "2026-04-28T18:18:29+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.10): admin module migrated to Express",
    "parents": "96908bb51ada7b0137859ad47b0bb914a94a1726",
    "type": "feat",
    "scope": "phase-13.10"
  },
  {
    "sha": "96908bb51ada7b0137859ad47b0bb914a94a1726",
    "shortSha": "96908bb",
    "dateIso": "2026-04-28T17:57:46+07:00",
    "author": "Bank",
    "subject": "fix(changelog): real SHAs for phase-* commit links + README rewrite",
    "parents": "c224d3276e2645b93f858c0d9e6da71bd8983bbb",
    "type": "fix",
    "scope": "changelog"
  },
  {
    "sha": "c224d3276e2645b93f858c0d9e6da71bd8983bbb",
    "shortSha": "c224d32",
    "dateIso": "2026-04-28T17:38:36+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.9.2): seller dashboard writes migrated to Express",
    "parents": "586410f44cf0419818238c21717c254f319ad83e",
    "type": "feat",
    "scope": "phase-13.9.2"
  },
  {
    "sha": "586410f44cf0419818238c21717c254f319ad83e",
    "shortSha": "586410f",
    "dateIso": "2026-04-28T16:57:54+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.9.1): seller dashboard reads migrated to Express",
    "parents": "fc2f52c317f0e123932aa2199474b000c2eb0c41",
    "type": "feat",
    "scope": "phase-13.9.1"
  },
  {
    "sha": "fc2f52c317f0e123932aa2199474b000c2eb0c41",
    "shortSha": "fc2f52c",
    "dateIso": "2026-04-28T16:16:08+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.8): messages migrated to Express",
    "parents": "7d8985033e3a753f54c6a06759448b54e02f335b",
    "type": "feat",
    "scope": "phase-13.8"
  },
  {
    "sha": "7d8985033e3a753f54c6a06759448b54e02f335b",
    "shortSha": "7d89850",
    "dateIso": "2026-04-28T15:54:44+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.7): favorites + stock alerts migrated to Express",
    "parents": "39dc2855b79b87c53da23cc36abbc8bc8e3ce0bc",
    "type": "feat",
    "scope": "phase-13.7"
  },
  {
    "sha": "39dc2855b79b87c53da23cc36abbc8bc8e3ce0bc",
    "shortSha": "39dc285",
    "dateIso": "2026-04-28T15:30:31+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.6.5): CPE241 rubric retrofit — triggers + views + roles + check constraints",
    "parents": "51c017efc197efaac1513ddf9babaa4742582c20",
    "type": "feat",
    "scope": "phase-13.6.5"
  },
  {
    "sha": "51c017efc197efaac1513ddf9babaa4742582c20",
    "shortSha": "51c017e",
    "dateIso": "2026-04-28T13:50:48+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.6): q&a + admin moderation migrated to Express",
    "parents": "56361ff4ca9691a37db3a79923f5c51974301740",
    "type": "feat",
    "scope": "phase-13.6"
  },
  {
    "sha": "56361ff4ca9691a37db3a79923f5c51974301740",
    "shortSha": "56361ff",
    "dateIso": "2026-04-28T13:06:53+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.5): reviews + admin moderation migrated to Express",
    "parents": "fcb7e49578d645a362125eaf693a699c049cba15",
    "type": "feat",
    "scope": "phase-13.5"
  },
  {
    "sha": "fcb7e49578d645a362125eaf693a699c049cba15",
    "shortSha": "fcb7e49",
    "dateIso": "2026-04-28T12:26:15+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.4): orders + checkout migrated to Express",
    "parents": "7e223dc5bd7738baea76a7ca55db846d00ba66e4",
    "type": "feat",
    "scope": "phase-13.4"
  },
  {
    "sha": "7e223dc5bd7738baea76a7ca55db846d00ba66e4",
    "shortSha": "7e223dc",
    "dateIso": "2026-04-28T12:09:33+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.2.1): forgot/reset password migrated to Express",
    "parents": "249162bfc4f1d797d1d91b523d81a3347183af0b",
    "type": "feat",
    "scope": "phase-13.2.1"
  },
  {
    "sha": "249162bfc4f1d797d1d91b523d81a3347183af0b",
    "shortSha": "249162b",
    "dateIso": "2026-04-28T11:19:00+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.3): cart + coupons migrated to Express",
    "parents": "1b934802e93cc35290e650ac5b71faf2a2f1118c",
    "type": "feat",
    "scope": "phase-13.3"
  },
  {
    "sha": "1b934802e93cc35290e650ac5b71faf2a2f1118c",
    "shortSha": "1b93480",
    "dateIso": "2026-04-28T10:54:12+07:00",
    "author": "Bank",
    "subject": "fix(phase-13.2): GET /auth/me leaked bcrypt hash in response body",
    "parents": "56c5ab568ec34b4fe9c708b94417fa75424a398f",
    "type": "fix",
    "scope": "phase-13.2"
  },
  {
    "sha": "56c5ab568ec34b4fe9c708b94417fa75424a398f",
    "shortSha": "56c5ab5",
    "dateIso": "2026-04-28T10:40:57+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.2): auth migrated to Express + cookie boundary",
    "parents": "7df6a948d5af3f48ea2821e5ca12badf7fc31106",
    "type": "feat",
    "scope": "phase-13.2"
  },
  {
    "sha": "7df6a948d5af3f48ea2821e5ca12badf7fc31106",
    "shortSha": "7df6a94",
    "dateIso": "2026-04-28T10:13:53+07:00",
    "author": "Bank",
    "subject": "feat(phase-13.1): backend separation — Express API + Next.js BFF",
    "parents": "c33c13894ce4854ea6865a0a26b832cd425f445c",
    "type": "feat",
    "scope": "phase-13.1"
  },
  {
    "sha": "c33c13894ce4854ea6865a0a26b832cd425f445c",
    "shortSha": "c33c138",
    "dateIso": "2026-04-26T13:45:15+07:00",
    "author": "Bank",
    "subject": "docs(qa-r3/F1): changelog card + clarify suppressHydrationWarning intent",
    "parents": "9b69363fe4f245d0ff5d4647b62efa3bc020488e",
    "type": "docs",
    "scope": "qa-r3/F1"
  },
  {
    "sha": "9b69363fe4f245d0ff5d4647b62efa3bc020488e",
    "shortSha": "9b69363",
    "dateIso": "2026-04-26T13:31:47+07:00",
    "author": "Bank",
    "subject": "fix(qa-r3/F1): narrow Image priority to 1-per-route to kill hydration mismatch",
    "parents": "bca14d767720cf6aed02f485667eee679cb2a98a",
    "type": "fix",
    "scope": "qa-r3/F1"
  },
  {
    "sha": "bca14d767720cf6aed02f485667eee679cb2a98a",
    "shortSha": "bca14d7",
    "dateIso": "2026-04-26T13:15:04+07:00",
    "author": "Bank",
    "subject": "fix(qa-r3/F1): suppressHydrationWarning on <html> for theme-bootstrap script",
    "parents": "4fc3648012f98ef92ea3daacec8d32fa06fa76f4",
    "type": "fix",
    "scope": "qa-r3/F1"
  },
  {
    "sha": "4fc3648012f98ef92ea3daacec8d32fa06fa76f4",
    "shortSha": "4fc3648",
    "dateIso": "2026-04-26T12:10:23+07:00",
    "author": "Bank",
    "subject": "docs(phase-12.2): add Phase 12.2 changelog card (User ban metadata)",
    "parents": "cba201a57ce8c24641530980e2d278d755038bee",
    "type": "docs",
    "scope": "phase-12.2"
  },
  {
    "sha": "cba201a57ce8c24641530980e2d278d755038bee",
    "shortSha": "cba201a",
    "dateIso": "2026-04-26T12:03:46+07:00",
    "author": "Bank",
    "subject": "feat(phase-12.2): user ban metadata — bannedAt + bannedReason",
    "parents": "ea752c5beffa39419f01921d72e650902131d15e",
    "type": "feat",
    "scope": "phase-12.2"
  },
  {
    "sha": "ea752c5beffa39419f01921d72e650902131d15e",
    "shortSha": "ea752c5",
    "dateIso": "2026-04-26T11:32:40+07:00",
    "author": "Bank",
    "subject": "docs(phase-11/F19+11.2): add changelog cards for today's two ships",
    "parents": "4808795b559a6f26ba40dc7618058e4fa57bd395",
    "type": "docs",
    "scope": "phase-11/F19+11.2"
  },
  {
    "sha": "4808795b559a6f26ba40dc7618058e4fa57bd395",
    "shortSha": "4808795",
    "dateIso": "2026-04-26T11:26:49+07:00",
    "author": "Bank",
    "subject": "feat(phase-11/F19): /browse mobile bottom-sheet + scroll-preserving filters",
    "parents": "1723b587ed115154ddc5a24c36f0a558b5ce92aa",
    "type": "feat",
    "scope": "phase-11/F19"
  },
  {
    "sha": "1723b587ed115154ddc5a24c36f0a558b5ce92aa",
    "shortSha": "1723b58",
    "dateIso": "2026-04-26T11:00:42+07:00",
    "author": "Bank",
    "subject": "fix(phase-11.2): moneyCompact() for KPI revenue cards (฿45.6K / ฿1.2M)",
    "parents": "9179eadd8612cb2db30a73b953684865a81c4460",
    "type": "fix",
    "scope": "phase-11.2"
  },
  {
    "sha": "9179eadd8612cb2db30a73b953684865a81c4460",
    "shortSha": "9179ead",
    "dateIso": "2026-04-26T10:44:08+07:00",
    "author": "Bank",
    "subject": "docs(phase-12.1): add Phase 12.1 + Phase 11.1 cards to /admin/changelog",
    "parents": "385de2375c144f3d8e7019dbd9f79564430794ab",
    "type": "docs",
    "scope": "phase-12.1"
  },
  {
    "sha": "385de2375c144f3d8e7019dbd9f79564430794ab",
    "shortSha": "385de23",
    "dateIso": "2026-04-26T10:32:50+07:00",
    "author": "Bank",
    "subject": "feat(phase-12.1): partial index on store(created_at) WHERE deleted_at IS NULL",
    "parents": "4f48627c42418df05feb38ea4ebd4ba8ed8d6291",
    "type": "feat",
    "scope": "phase-12.1"
  },
  {
    "sha": "4f48627c42418df05feb38ea4ebd4ba8ed8d6291",
    "shortSha": "4f48627",
    "dateIso": "2026-04-26T10:06:02+07:00",
    "author": "Bank",
    "subject": "fix(phase-11.1): /browse grid overflow + StatCard highlight font",
    "parents": "ef93668dc93fc7427f58084f23001c1b923678a5",
    "type": "fix",
    "scope": "phase-11.1"
  },
  {
    "sha": "ef93668dc93fc7427f58084f23001c1b923678a5",
    "shortSha": "ef93668",
    "dateIso": "2026-04-26T09:38:05+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/run-2): drop /not-found routable page so URL falls through to framework 404",
    "parents": "4fd297bd9a08c458b0468b14ec248b763eb91f40",
    "type": "fix",
    "scope": "phase-11/run-2"
  },
  {
    "sha": "4fd297bd9a08c458b0468b14ec248b763eb91f40",
    "shortSha": "4fd297b",
    "dateIso": "2026-04-26T09:32:28+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/run-2): force-dynamic on /not-found so notFound() actually emits 404",
    "parents": "5f4a878359f929e992ea250542ab5f393811c6e2",
    "type": "fix",
    "scope": "phase-11/run-2"
  },
  {
    "sha": "5f4a878359f929e992ea250542ab5f393811c6e2",
    "shortSha": "5f4a878",
    "dateIso": "2026-04-26T09:27:21+07:00",
    "author": "Bank",
    "subject": "docs(phase-11/run-2): add Phase 11 run #2 card to /admin/changelog",
    "parents": "eb5b7a7f925cfa2e0bfbb897a8800b20faf56442",
    "type": "docs",
    "scope": "phase-11/run-2"
  },
  {
    "sha": "eb5b7a7f925cfa2e0bfbb897a8800b20faf56442",
    "shortSha": "eb5b7a7",
    "dateIso": "2026-04-26T09:20:10+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/bug-fixer): F1 F2 F3 F5 F8 F12 F14 F21 F22 — soft-delete predicates, profanity guard, cart badge, true 404",
    "parents": "5686162b71e5641c06ae90c77739dad940cb4f3e",
    "type": "fix",
    "scope": "phase-11/bug-fixer"
  },
  {
    "sha": "5686162b71e5641c06ae90c77739dad940cb4f3e",
    "shortSha": "5686162",
    "dateIso": "2026-04-26T09:18:07+07:00",
    "author": "Bank",
    "subject": "perf(phase-11/perf-tuner): F4, F10, F13 — image priority hints + drop /admin/stores HTTP hop",
    "parents": "ec0c3328a73efcb14724367d2692c790cfc01977",
    "type": "perf",
    "scope": "phase-11/perf-tuner"
  },
  {
    "sha": "ec0c3328a73efcb14724367d2692c790cfc01977",
    "shortSha": "ec0c332",
    "dateIso": "2026-04-26T09:17:41+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/content-copy): F9, F17, F18 — coupon hint i18n, changelog 'today' count, favourites→favorites",
    "parents": "45c0ad1b9a9e395c71ec334f18ee5977f276efaf",
    "type": "fix",
    "scope": "phase-11/content-copy"
  },
  {
    "sha": "45c0ad1b9a9e395c71ec334f18ee5977f276efaf",
    "shortSha": "45c0ad1",
    "dateIso": "2026-04-26T09:17:17+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/design-cohesion): F7, F16 — Banknote icon for baht stats, equalize home grid",
    "parents": "7e80664ea13c04477766d74146964b3e5ba1e44f",
    "type": "fix",
    "scope": "phase-11/design-cohesion"
  },
  {
    "sha": "7e80664ea13c04477766d74146964b3e5ba1e44f",
    "shortSha": "7e80664",
    "dateIso": "2026-04-26T09:17:00+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/ux-polish): F6, F11, F15 — multi-role badges, drop Sort Apply, Avatar primitive",
    "parents": "540467475cf9c895e867857ee4f168a529133448",
    "type": "fix",
    "scope": "phase-11/ux-polish"
  },
  {
    "sha": "540467475cf9c895e867857ee4f168a529133448",
    "shortSha": "5404674",
    "dateIso": "2026-04-25T21:02:31+07:00",
    "author": "Bank",
    "subject": "docs(phase-11): add Phase 11 QA-workflow card to /admin/changelog",
    "parents": "d59e44d6be823fb605907d2be6606472a5278d9b",
    "type": "docs",
    "scope": "phase-11"
  },
  {
    "sha": "d59e44d6be823fb605907d2be6606472a5278d9b",
    "shortSha": "d59e44d",
    "dateIso": "2026-04-25T20:44:46+07:00",
    "author": "Bank",
    "subject": "feat(phase-11/orchestrator): F22 SortSelect auto-submit + gitignore reports/",
    "parents": "2362930c743898900dcba09344b60fc15cb3aa81",
    "type": "feat",
    "scope": "phase-11/orchestrator"
  },
  {
    "sha": "2362930c743898900dcba09344b60fc15cb3aa81",
    "shortSha": "2362930",
    "dateIso": "2026-04-25T20:41:53+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/bug-fixer): F1, F2, F3, F6, F8, F9, F10, F14, F15, F23 — junk cleanup + cascade fix + counter unify + slug resolver",
    "parents": "b8b5068efce02dfcb10d00bc170e4d75bb6bd113",
    "type": "fix",
    "scope": "phase-11/bug-fixer"
  },
  {
    "sha": "b8b5068efce02dfcb10d00bc170e4d75bb6bd113",
    "shortSha": "b8b5068",
    "dateIso": "2026-04-25T20:40:16+07:00",
    "author": "Bank",
    "subject": "feat(phase-11/design-cohesion): F18, F21, F26, F27 — flatten variants, drop THB pill, balance browse grid, neutralise lock banner",
    "parents": "d16b891ab6b961c89ecea3c6727b078cc644864c",
    "type": "feat",
    "scope": "phase-11/design-cohesion"
  },
  {
    "sha": "d16b891ab6b961c89ecea3c6727b078cc644864c",
    "shortSha": "d16b891",
    "dateIso": "2026-04-25T20:39:16+07:00",
    "author": "Bank",
    "subject": "feat(phase-11/ux-polish): F4, F11, F12, F13, F16, F19 — ConfirmDialog primitive + guest-state hardening",
    "parents": "d1b06a9e27d591d1fe9cdf3603088f7ec3e864bf",
    "type": "feat",
    "scope": "phase-11/ux-polish"
  },
  {
    "sha": "d1b06a9e27d591d1fe9cdf3603088f7ec3e864bf",
    "shortSha": "d1b06a9",
    "dateIso": "2026-04-25T20:38:08+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/copy+i18n): F2, F7, F17, F20, F24, F25 — friendlier empties + locale-pinned dates",
    "parents": "a43207e66448f46484f8c473e050f79effbdaad0",
    "type": "fix",
    "scope": "phase-11/copy+i18n"
  },
  {
    "sha": "a43207e66448f46484f8c473e050f79effbdaad0",
    "shortSha": "a43207e",
    "dateIso": "2026-04-25T20:37:01+07:00",
    "author": "Bank",
    "subject": "perf(phase-11/perf-tuner): F28 — kill /profile/edit skeleton flash",
    "parents": "4162e5fe3658f41cd06ff4a46d0c7d370a80d655",
    "type": "perf",
    "scope": "phase-11/perf-tuner"
  },
  {
    "sha": "4162e5fe3658f41cd06ff4a46d0c7d370a80d655",
    "shortSha": "4162e5f",
    "dateIso": "2026-04-25T20:35:12+07:00",
    "author": "Bank",
    "subject": "fix(phase-11/a11y): F5 — light-theme hero contrast (DIGITAL ~17:1)",
    "parents": "1ba0cdcad3643fb1d93bd29d79224db472b0dd9c",
    "type": "fix",
    "scope": "phase-11/a11y"
  },
  {
    "sha": "1ba0cdcad3643fb1d93bd29d79224db472b0dd9c",
    "shortSha": "1ba0cdc",
    "dateIso": "2026-04-23T18:23:24+07:00",
    "author": "Bank",
    "subject": "fix: browse grid 4-cols at lg + new 'purchase' sound cue on order success",
    "parents": "9cd06a23847edfc1aeec5b63d9e7a923cc1bd196",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "9cd06a23847edfc1aeec5b63d9e7a923cc1bd196",
    "shortSha": "9cd06a2",
    "dateIso": "2026-04-23T18:09:46+07:00",
    "author": "Bank",
    "subject": "feat(features): refresh /features page with Phase 9+10 + visual mockups",
    "parents": "d3538ef03fd0b7954b71b365c106514a3d755774",
    "type": "feat",
    "scope": "features"
  },
  {
    "sha": "d3538ef03fd0b7954b71b365c106514a3d755774",
    "shortSha": "d3538ef",
    "dateIso": "2026-04-23T18:00:11+07:00",
    "author": "Bank",
    "subject": "fix: server timezone GMT+7 + sound effects on live deploy",
    "parents": "487f823b21c7cfec1d32805d8929d147eb8b0301",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "487f823b21c7cfec1d32805d8929d147eb8b0301",
    "shortSha": "487f823",
    "dateIso": "2026-04-23T13:45:37+07:00",
    "author": "Bank",
    "subject": "feat(phase-10): FileImageInput compact thumbnail + Phase 10 changelog entry",
    "parents": "7be59cbbd091f7b320bc5bad8568ee4e6ddb70c9",
    "type": "feat",
    "scope": "phase-10"
  },
  {
    "sha": "7be59cbbd091f7b320bc5bad8568ee4e6ddb70c9",
    "shortSha": "7be59cb",
    "dateIso": "2026-04-23T13:31:08+07:00",
    "author": "Bank",
    "subject": "feat(phase-10): messaging discoverability — buyer inbox, TopNav icon, Message store CTAs",
    "parents": "d6782fb127ffc6dcc39be8fceb000c731312383d",
    "type": "feat",
    "scope": "phase-10"
  },
  {
    "sha": "d6782fb127ffc6dcc39be8fceb000c731312383d",
    "shortSha": "d6782fb",
    "dateIso": "2026-04-23T12:54:00+07:00",
    "author": "Bank",
    "subject": "feat(phase-10): admin tables — DataTable + ActionRow + sidebar tokens",
    "parents": "d91ce9bc247c1b5e36be56d32b7128d9322772e5",
    "type": "feat",
    "scope": "phase-10"
  },
  {
    "sha": "d91ce9bc247c1b5e36be56d32b7128d9322772e5",
    "shortSha": "d91ce9b",
    "dateIso": "2026-04-23T12:52:29+07:00",
    "author": "Bank",
    "subject": "feat(phase-10): seller forms — apply primitives, add live previews, add VariantRow",
    "parents": "fd8a7283e32de10aabfded7631b0cbeeb1b683f7",
    "type": "feat",
    "scope": "phase-10"
  },
  {
    "sha": "fd8a7283e32de10aabfded7631b0cbeeb1b683f7",
    "shortSha": "fd8a728",
    "dateIso": "2026-04-23T11:14:27+07:00",
    "author": "Bank",
    "subject": "feat(phase-10): authoring primitives — FormSection, TextInput, DataTable, VariantRow, PreviewPane, ActionRow",
    "parents": "83caf522fe88bda3f6b49407787d3a334f50bebc",
    "type": "feat",
    "scope": "phase-10"
  },
  {
    "sha": "83caf522fe88bda3f6b49407787d3a334f50bebc",
    "shortSha": "83caf52",
    "dateIso": "2026-04-23T11:06:57+07:00",
    "author": "Bank",
    "subject": "feat(phase-10): admin moderation — delete/edit reviews + Q&A on product page",
    "parents": "57ba66e2ccf9ad1951552769d5560dc6b9bd7eee",
    "type": "feat",
    "scope": "phase-10"
  },
  {
    "sha": "57ba66e2ccf9ad1951552769d5560dc6b9bd7eee",
    "shortSha": "57ba66e",
    "dateIso": "2026-04-23T10:45:38+07:00",
    "author": "Bank",
    "subject": "fix(phase-10): Q&A label reflects real answerer role (admin vs seller)",
    "parents": "8b7528efcc26645a91b77b3507d7bf562aa7111a",
    "type": "fix",
    "scope": "phase-10"
  },
  {
    "sha": "8b7528efcc26645a91b77b3507d7bf562aa7111a",
    "shortSha": "8b7528e",
    "dateIso": "2026-04-23T10:33:33+07:00",
    "author": "Bank",
    "subject": "feat(phase-9/wave-3): rebrand transactional surfaces — product, store, cart, seller, admin",
    "parents": "4b39e846eb74eecb3a4cad4978e5129ceac64a8a",
    "type": "feat",
    "scope": "phase-9/wave-3"
  },
  {
    "sha": "4b39e846eb74eecb3a4cad4978e5129ceac64a8a",
    "shortSha": "4b39e84",
    "dateIso": "2026-04-23T10:33:12+07:00",
    "author": "Bank",
    "subject": "feat(phase-9/wave-3): rebrand marketing surfaces — home asymmetric grid, browse filters, 404, /health, /features",
    "parents": "bdfc4aec142a8b6bad5eb94ca5410b299c0ed2f8",
    "type": "feat",
    "scope": "phase-9/wave-3"
  },
  {
    "sha": "bdfc4aec142a8b6bad5eb94ca5410b299c0ed2f8",
    "shortSha": "bdfc4ae",
    "dateIso": "2026-04-23T10:12:48+07:00",
    "author": "Bank",
    "subject": "fix(phase-9): 6 UX papercuts — mobile grid, profile-edit stack, variant trash hint",
    "parents": "4880438e9902f249c8b64da36e01353c55210859",
    "type": "fix",
    "scope": "phase-9"
  },
  {
    "sha": "4880438e9902f249c8b64da36e01353c55210859",
    "shortSha": "4880438",
    "dateIso": "2026-04-23T10:12:23+07:00",
    "author": "Bank",
    "subject": "fix(phase-9): 5 audit bugs — minRating pagination, cart checkout busy, save-for-later, coupon, sort cast",
    "parents": "6466b232a207772d9846ee99e108224ba24a02f0",
    "type": "fix",
    "scope": "phase-9"
  },
  {
    "sha": "6466b232a207772d9846ee99e108224ba24a02f0",
    "shortSha": "6466b23",
    "dateIso": "2026-04-23T10:11:55+07:00",
    "author": "Bank",
    "subject": "feat(phase-9/wave-2): rebrand cards — ProductCard variants, mint Badge, asymmetric StatCard, FlatCard primitive",
    "parents": "98498125bafb767dd401e55cad6c5de8b9f12082",
    "type": "feat",
    "scope": "phase-9/wave-2"
  },
  {
    "sha": "98498125bafb767dd401e55cad6c5de8b9f12082",
    "shortSha": "9849812",
    "dateIso": "2026-04-23T10:11:26+07:00",
    "author": "Bank",
    "subject": "feat(phase-9/wave-2): rebrand shell + chrome — TopNav, Footer, controls, Prompt font",
    "parents": "36e0f46dc174891d839ab0fab9b302d788f92d77",
    "type": "feat",
    "scope": "phase-9/wave-2"
  },
  {
    "sha": "36e0f46dc174891d839ab0fab9b302d788f92d77",
    "shortSha": "36e0f46",
    "dateIso": "2026-04-23T09:49:36+07:00",
    "author": "Bank",
    "subject": "feat(phase-9/wave-1): design-system foundation — palette + tokens + playbook",
    "parents": "70513e7c9faab0458a9e6db963363fe4966b8466",
    "type": "feat",
    "scope": "phase-9/wave-1"
  },
  {
    "sha": "70513e7c9faab0458a9e6db963363fe4966b8466",
    "shortSha": "70513e7",
    "dateIso": "2026-04-23T08:59:17+07:00",
    "author": "Bank",
    "subject": "docs(admin): add Batch G entry to /admin/changelog",
    "parents": "42f93cb5d57073ad8645276da957e0906e84af21",
    "type": "docs",
    "scope": "admin"
  },
  {
    "sha": "42f93cb5d57073ad8645276da957e0906e84af21",
    "shortSha": "42f93cb",
    "dateIso": "2026-04-23T08:48:16+07:00",
    "author": "Bank",
    "subject": "feat(batch-g): tests — Vitest unit suite + Playwright 4-persona smoke",
    "parents": "339616f9c76a89fbde99647e9cf079081ffa52e9",
    "type": "feat",
    "scope": "batch-g"
  },
  {
    "sha": "339616f9c76a89fbde99647e9cf079081ffa52e9",
    "shortSha": "339616f",
    "dateIso": "2026-04-23T08:26:46+07:00",
    "author": "Bank",
    "subject": "docs(admin): add Batch F entry to /admin/changelog",
    "parents": "5609aecd2bd6fa8c1c1f4faa68faf90c5c2f5edf",
    "type": "docs",
    "scope": "admin"
  },
  {
    "sha": "5609aecd2bd6fa8c1c1f4faa68faf90c5c2f5edf",
    "shortSha": "5609aec",
    "dateIso": "2026-04-23T08:22:01+07:00",
    "author": "Bank",
    "subject": "feat(batch-f): observability — Sentry + Plausible + public /health page",
    "parents": "99a9e13d5d5a45b44d7c7d6f9e268d8377052ea6",
    "type": "feat",
    "scope": "batch-f"
  },
  {
    "sha": "99a9e13d5d5a45b44d7c7d6f9e268d8377052ea6",
    "shortSha": "99a9e13",
    "dateIso": "2026-04-23T08:03:19+07:00",
    "author": "Bank",
    "subject": "docs(admin): add Batch E entry to /admin/changelog",
    "parents": "d4d7c1a4efaa22710f184d551f81ab4eab7f905f",
    "type": "docs",
    "scope": "admin"
  },
  {
    "sha": "d4d7c1a4efaa22710f184d551f81ab4eab7f905f",
    "shortSha": "d4d7c1a",
    "dateIso": "2026-04-23T07:57:03+07:00",
    "author": "Bank",
    "subject": "feat(batch-e/2): light mode toggle + scoped TH/EN i18n",
    "parents": "7276a3141558ebdcf42c2e7dff3e5bc2aefe3c80",
    "type": "feat",
    "scope": "batch-e/2"
  },
  {
    "sha": "7276a3141558ebdcf42c2e7dff3e5bc2aefe3c80",
    "shortSha": "7276a31",
    "dateIso": "2026-04-23T07:46:56+07:00",
    "author": "Bank",
    "subject": "feat(batch-e/1): PWA manifest, sitemap+robots, custom 404, skip-to-content, focus-trap",
    "parents": "8623e4a3453519cb26d47f35b1ad5c16cc8b02de",
    "type": "feat",
    "scope": "batch-e/1"
  },
  {
    "sha": "8623e4a3453519cb26d47f35b1ad5c16cc8b02de",
    "shortSha": "8623e4a",
    "dateIso": "2026-04-22T12:48:00+07:00",
    "author": "Bank",
    "subject": "fix(admin): /admin/changelog must be dynamic, not static",
    "parents": "f1af63207953c8bb092dc3a1b97e5d6404c3b234",
    "type": "fix",
    "scope": "admin"
  },
  {
    "sha": "f1af63207953c8bb092dc3a1b97e5d6404c3b234",
    "shortSha": "f1af632",
    "dateIso": "2026-04-22T12:40:12+07:00",
    "author": "Bank",
    "subject": "fix(auth): role checks read live DB role, not stale JWT",
    "parents": "4d01572dacb78ecbae513014e1cd1cbe75fe6cc9",
    "type": "fix",
    "scope": "auth"
  },
  {
    "sha": "4d01572dacb78ecbae513014e1cd1cbe75fe6cc9",
    "shortSha": "4d01572",
    "dateIso": "2026-04-22T12:31:47+07:00",
    "author": "Bank",
    "subject": "feat(admin): /admin/changelog — visual recap of today's 6 batches (admin-only)",
    "parents": "5ee58b168f2d36d8a0ef43aaded141c6de25dd38",
    "type": "feat",
    "scope": "admin"
  },
  {
    "sha": "5ee58b168f2d36d8a0ef43aaded141c6de25dd38",
    "shortSha": "5ee58b1",
    "dateIso": "2026-04-22T12:24:12+07:00",
    "author": "Bank",
    "subject": "feat(batch-d): trust & security — rate limit, password reset, soft-delete + audit, Turnstile, GDPR export",
    "parents": "275863c3cda4c235c1b90a711830e17e48bb80df",
    "type": "feat",
    "scope": "batch-d"
  },
  {
    "sha": "275863c3cda4c235c1b90a711830e17e48bb80df",
    "shortSha": "275863c",
    "dateIso": "2026-04-22T12:01:15+07:00",
    "author": "Bank",
    "subject": "fix(auth): keep admin role when admin opens a store + prominent Admin button + smoother scroll",
    "parents": "4f832ea139a7d6444ee4d962d4bb95bdd7a7048b",
    "type": "fix",
    "scope": "auth"
  },
  {
    "sha": "4f832ea139a7d6444ee4d962d4bb95bdd7a7048b",
    "shortSha": "4f832ea",
    "dateIso": "2026-04-22T11:19:01+07:00",
    "author": "Bank",
    "subject": "feat(batch-c): buyer growth — Q&A, sample, related, compare, gift, rating filter, restock",
    "parents": "813d3717fedc9242677173c4232537d10fcd4bfa",
    "type": "feat",
    "scope": "batch-c"
  },
  {
    "sha": "813d3717fedc9242677173c4232537d10fcd4bfa",
    "shortSha": "813d371",
    "dateIso": "2026-04-22T09:42:43+07:00",
    "author": "Bank",
    "subject": "feat(batch-b): seller tools — duplicate, pause, inbox, coupon report, CSV, low-stock, bulk edit",
    "parents": "cda174d71c8ee19d2e4ec7a754fd6b711e7608f7",
    "type": "feat",
    "scope": "batch-b"
  },
  {
    "sha": "cda174d71c8ee19d2e4ec7a754fd6b711e7608f7",
    "shortSha": "cda174d",
    "dateIso": "2026-04-22T08:54:36+07:00",
    "author": "Bank",
    "subject": "feat(batch-a): quick wins — recently-viewed, share, social proof, save-for-later, keyboard shortcuts, profile edit, change password",
    "parents": "a4cc31e3cc017ca2ccd11e57cc6188a236266ccd",
    "type": "feat",
    "scope": "batch-a"
  },
  {
    "sha": "a4cc31e3cc017ca2ccd11e57cc6188a236266ccd",
    "shortSha": "a4cc31e",
    "dateIso": "2026-04-22T07:39:48+07:00",
    "author": "Bank",
    "subject": "chore(fly): revert memory back to 512mb to stay within free credit",
    "parents": "4a5496a5e7d36f7c4487cfdaa8aa49676c3236bf",
    "type": "chore",
    "scope": "fly"
  },
  {
    "sha": "4a5496a5e7d36f7c4487cfdaa8aa49676c3236bf",
    "shortSha": "4a5496a",
    "dateIso": "2026-04-22T07:34:32+07:00",
    "author": "Bank",
    "subject": "chore(fly): bump fly.toml memory to 1gb to match deployed reality",
    "parents": "b75a6b3a798865ff8e80a41a51311c8a06ce6fe8",
    "type": "chore",
    "scope": "fly"
  },
  {
    "sha": "b75a6b3a798865ff8e80a41a51311c8a06ce6fe8",
    "shortSha": "b75a6b3",
    "dateIso": "2026-04-22T07:17:55+07:00",
    "author": "Bank",
    "subject": "perf(ui): cut backdrop-blur radii + slim shadow blurs to fix scroll stutter",
    "parents": "c4d3d6fcb975a44c843c85d1e95d7163f771ef40",
    "type": "perf",
    "scope": "ui"
  },
  {
    "sha": "c4d3d6fcb975a44c843c85d1e95d7163f771ef40",
    "shortSha": "c4d3d6f",
    "dateIso": "2026-04-22T07:03:25+07:00",
    "author": "Bank",
    "subject": "fix(fly): release_command calls prisma's JS entry directly",
    "parents": "e1e6d077ad6094be7de4fb9fb85c6ee35d808409",
    "type": "fix",
    "scope": "fly"
  },
  {
    "sha": "e1e6d077ad6094be7de4fb9fb85c6ee35d808409",
    "shortSha": "e1e6d07",
    "dateIso": "2026-04-22T06:34:00+07:00",
    "author": "Bank",
    "subject": "fix(fly): switch app to listen on 8080 to match live Fly config",
    "parents": "a5e90f29b74070ab873c461d436bb5b38d92ea0f",
    "type": "fix",
    "scope": "fly"
  },
  {
    "sha": "a5e90f29b74070ab873c461d436bb5b38d92ea0f",
    "shortSha": "a5e90f2",
    "dateIso": "2026-04-22T06:11:57+07:00",
    "author": "Bank",
    "subject": "fix(deploy): unblock Fly Docker build (public dir + experimental key + register dynamic)",
    "parents": "d1e96095fd46fb686a5833df242f84218e8b39f2",
    "type": "fix",
    "scope": "deploy"
  },
  {
    "sha": "d1e96095fd46fb686a5833df242f84218e8b39f2",
    "shortSha": "d1e9609",
    "dateIso": "2026-04-22T05:57:59+07:00",
    "author": "Bank",
    "subject": "fix(docker): skip postinstall scripts in deps stage",
    "parents": "d38f3137679bb329706f6f9d3fe3f1d3346a2526",
    "type": "fix",
    "scope": "docker"
  },
  {
    "sha": "d38f3137679bb329706f6f9d3fe3f1d3346a2526",
    "shortSha": "d38f313",
    "dateIso": "2026-04-22T05:26:26+07:00",
    "author": "Bank",
    "subject": "feat(deploy): Fly.io configuration (Singapore region)",
    "parents": "80de115dd59b6b40d31ade9c2df5974cf6554b5d",
    "type": "feat",
    "scope": "deploy"
  },
  {
    "sha": "80de115dd59b6b40d31ade9c2df5974cf6554b5d",
    "shortSha": "80de115",
    "dateIso": "2026-04-22T05:09:20+07:00",
    "author": "Bank",
    "subject": "perf: pin Vercel function region to hnd1 (Tokyo)",
    "parents": "b9825bfe5c6620e5555a3e9bdeb1e81bb3af755f",
    "type": "perf",
    "scope": null
  },
  {
    "sha": "b9825bfe5c6620e5555a3e9bdeb1e81bb3af755f",
    "shortSha": "b9825bf",
    "dateIso": "2026-04-22T05:05:37+07:00",
    "author": "Bank",
    "subject": "fix(seller): add missing PATCH /api/seller/store handler",
    "parents": "d6985d842bcf4d46eef2ebbc657719a7d1548de1",
    "type": "fix",
    "scope": "seller"
  },
  {
    "sha": "d6985d842bcf4d46eef2ebbc657719a7d1548de1",
    "shortSha": "d6985d8",
    "dateIso": "2026-04-22T04:57:19+07:00",
    "author": "Bank",
    "subject": "feat(cart): recommend popular products when cart is empty",
    "parents": "b466e6a05a9e61506abbf515c13c839bf2e3b5da",
    "type": "feat",
    "scope": "cart"
  },
  {
    "sha": "b466e6a05a9e61506abbf515c13c839bf2e3b5da",
    "shortSha": "b466e6a",
    "dateIso": "2026-04-22T04:55:38+07:00",
    "author": "Bank",
    "subject": "perf(batch-0): keep-warm cron + parallelised product page + Prisma global + unpooled migrate",
    "parents": "61690b7c8fd3b0f8ba1ee9b305a57cb7d3dc5e2a",
    "type": "perf",
    "scope": "batch-0"
  },
  {
    "sha": "61690b7c8fd3b0f8ba1ee9b305a57cb7d3dc5e2a",
    "shortSha": "61690b7",
    "dateIso": "2026-04-22T04:33:21+07:00",
    "author": "Bank",
    "subject": "feat(seller): refund an order (e.g. out of stock)",
    "parents": "d8963658e0fb8299c43300a38497f1b6ec750297",
    "type": "feat",
    "scope": "seller"
  },
  {
    "sha": "d8963658e0fb8299c43300a38497f1b6ec750297",
    "shortSha": "d896365",
    "dateIso": "2026-04-22T04:31:43+07:00",
    "author": "Bank",
    "subject": "feat(orders): tabbed grouping — All / In progress / Completed / Cancelled",
    "parents": "b963d3593ff2cebf4f8dc9738fad2df113d7bfac",
    "type": "feat",
    "scope": "orders"
  },
  {
    "sha": "b963d3593ff2cebf4f8dc9738fad2df113d7bfac",
    "shortSha": "b963d35",
    "dateIso": "2026-04-22T04:29:52+07:00",
    "author": "Bank",
    "subject": "feat(ux): sound effects + floating 'added' bubble",
    "parents": "a372cdf864b267545d9b3d57e5a01b6e83590220",
    "type": "feat",
    "scope": "ux"
  },
  {
    "sha": "a372cdf864b267545d9b3d57e5a01b6e83590220",
    "shortSha": "a372cdf",
    "dateIso": "2026-04-21T21:22:57+07:00",
    "author": "Bank",
    "subject": "feat(seller): /seller/analytics — 30-day chart + per-product table + top buyers",
    "parents": "f57d2b72f447d0255473588035dd82459cd9b988",
    "type": "feat",
    "scope": "seller"
  },
  {
    "sha": "f57d2b72f447d0255473588035dd82459cd9b988",
    "shortSha": "f57d2b7",
    "dateIso": "2026-04-21T21:20:59+07:00",
    "author": "Bank",
    "subject": "feat(polish): expanded register, tag chips on receipt, expandable description",
    "parents": "22a8a77c94cff1001945ad4af4a23ba3131ccbd6",
    "type": "feat",
    "scope": "polish"
  },
  {
    "sha": "22a8a77c94cff1001945ad4af4a23ba3131ccbd6",
    "shortSha": "22a8a77",
    "dateIso": "2026-04-21T21:15:33+07:00",
    "author": "Bank",
    "subject": "feat: favourites / wishlist",
    "parents": "3bd306bc87d40d59326c67997d4abbf7012102b2",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "3bd306bc87d40d59326c67997d4abbf7012102b2",
    "shortSha": "3bd306b",
    "dateIso": "2026-04-21T20:53:30+07:00",
    "author": "Bank",
    "subject": "feat(seller): mark orders fulfilled / cancelled from orders inbox",
    "parents": "49ed579985c6b00c40cb88e9095bb40709c6eb23",
    "type": "feat",
    "scope": "seller"
  },
  {
    "sha": "49ed579985c6b00c40cb88e9095bb40709c6eb23",
    "shortSha": "49ed579",
    "dateIso": "2026-04-21T20:50:48+07:00",
    "author": "Bank",
    "subject": "feat(seller): edit + delete products",
    "parents": "2fe5ab0a6b4941198dc0f01d69cf1470d3ed7b45",
    "type": "feat",
    "scope": "seller"
  },
  {
    "sha": "2fe5ab0a6b4941198dc0f01d69cf1470d3ed7b45",
    "shortSha": "2fe5ab0",
    "dateIso": "2026-04-21T20:42:40+07:00",
    "author": "Bank",
    "subject": "feat(product): stock-aware qty input + digital lock on AddToCart",
    "parents": "7fa58e97eca1a75e3b06803ac332c7c8b597c83c",
    "type": "feat",
    "scope": "product"
  },
  {
    "sha": "7fa58e97eca1a75e3b06803ac332c7c8b597c83c",
    "shortSha": "7fa58e9",
    "dateIso": "2026-04-21T20:29:11+07:00",
    "author": "Bank",
    "subject": "feat(cart): checkboxes for partial checkout, typed qty, per-store coupon scope",
    "parents": "ec5c98cecf93af1f091605476c21a8a703309a0d",
    "type": "feat",
    "scope": "cart"
  },
  {
    "sha": "ec5c98cecf93af1f091605476c21a8a703309a0d",
    "shortSha": "ec5c98c",
    "dateIso": "2026-04-21T14:29:56+07:00",
    "author": "Bank",
    "subject": "feat(docs): /features page — complete UI tour grouped by role",
    "parents": "c1d67a64cb33f376d3f3cd6bb554ec9172cc60f0",
    "type": "feat",
    "scope": "docs"
  },
  {
    "sha": "c1d67a64cb33f376d3f3cd6bb554ec9172cc60f0",
    "shortSha": "c1d67a6",
    "dateIso": "2026-04-21T13:57:41+07:00",
    "author": "Bank",
    "subject": "feat(admin): manage users, stores, and transactions in-place",
    "parents": "cc86c44fac9a08a7e98faa76be85c2b63abb469e",
    "type": "feat",
    "scope": "admin"
  },
  {
    "sha": "cc86c44fac9a08a7e98faa76be85c2b63abb469e",
    "shortSha": "cc86c44",
    "dateIso": "2026-04-21T13:51:36+07:00",
    "author": "Bank",
    "subject": "feat(admin): 14-day revenue chart on overview, more recent transactions",
    "parents": "ad29de6660314cb9a33f8e3b20416b89b156188e",
    "type": "feat",
    "scope": "admin"
  },
  {
    "sha": "ad29de6660314cb9a33f8e3b20416b89b156188e",
    "shortSha": "ad29de6",
    "dateIso": "2026-04-21T13:48:46+07:00",
    "author": "Bank",
    "subject": "fix: keep DiceBear SVG avatars on the unoptimised path",
    "parents": "871deb9c43418e768973136b6f888cc02de35bba",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "871deb9c43418e768973136b6f888cc02de35bba",
    "shortSha": "871deb9",
    "dateIso": "2026-04-21T13:41:57+07:00",
    "author": "Bank",
    "subject": "perf: enable image optimisation, cache reference data, parallelise store, slim queries, add 6 loading skeletons",
    "parents": "2bf6b0b17d113bd8d66b178cca6b9ddf8b9b3ba0",
    "type": "perf",
    "scope": null
  },
  {
    "sha": "2bf6b0b17d113bd8d66b178cca6b9ddf8b9b3ba0",
    "shortSha": "2bf6b0b",
    "dateIso": "2026-04-21T13:15:46+07:00",
    "author": "Bank",
    "subject": "fix(seller): router.refresh after create so destination list re-reads fresh data",
    "parents": "4d3e83666116bab42b216d21b4f593beb0cdcdbc",
    "type": "fix",
    "scope": "seller"
  },
  {
    "sha": "4d3e83666116bab42b216d21b4f593beb0cdcdbc",
    "shortSha": "4d3e836",
    "dateIso": "2026-04-21T13:11:49+07:00",
    "author": "Bank",
    "subject": "chore: trigger contributors re-index",
    "parents": "a8e49af95a7b5735408f9ec95cc1100b80f2ac25",
    "type": "chore",
    "scope": null
  },
  {
    "sha": "a8e49af95a7b5735408f9ec95cc1100b80f2ac25",
    "shortSha": "a8e49af",
    "dateIso": "2026-04-21T13:06:24+07:00",
    "author": "Bank",
    "subject": "feat(seller): allow file upload for product images",
    "parents": "63bc3d6a791bc13bcb1585d6786ce655c00c0c35",
    "type": "feat",
    "scope": "seller"
  },
  {
    "sha": "63bc3d6a791bc13bcb1585d6786ce655c00c0c35",
    "shortSha": "63bc3d6",
    "dateIso": "2026-04-21T12:33:07+07:00",
    "author": "Bank",
    "subject": "feat: review-from-order, store image upload, broken-image fix, perf, auth UX",
    "parents": "2f195763c2ab6dfd122623b6a16bbb50db18cb46",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "2f195763c2ab6dfd122623b6a16bbb50db18cb46",
    "shortSha": "2f19576",
    "dateIso": "2026-04-21T11:55:01+07:00",
    "author": "Bank",
    "subject": "feat: 5 missing pages + skeletons + footer/category UX fixes",
    "parents": "44d696c8b84c7b491827184e24b0790a8a606564",
    "type": "feat",
    "scope": null
  },
  {
    "sha": "44d696c8b84c7b491827184e24b0790a8a606564",
    "shortSha": "44d696c",
    "dateIso": "2026-04-21T10:26:42+07:00",
    "author": "Bank",
    "subject": "feat(ui): full visual port to friend's neo-luxury theme + 3 new design pages",
    "parents": "887ff4d9330ef808bf133582de27ae9da939d963",
    "type": "feat",
    "scope": "ui"
  },
  {
    "sha": "887ff4d9330ef808bf133582de27ae9da939d963",
    "shortSha": "887ff4d",
    "dateIso": "2026-04-21T09:29:09+07:00",
    "author": "Bank",
    "subject": "chore(deps): bump next 14.2.18 → 14.2.35 for security patches",
    "parents": "66d0dbe6cfae826286966fc40625cb03ea39cb5b",
    "type": "chore",
    "scope": "deps"
  },
  {
    "sha": "66d0dbe6cfae826286966fc40625cb03ea39cb5b",
    "shortSha": "66d0dbe",
    "dateIso": "2026-04-21T09:00:01+07:00",
    "author": "Bank",
    "subject": "perf+fix: faster auth, themed product images, error/404 pages, input validation",
    "parents": "333bf65c0ab3d64fc1891093c66ecb36f9257879",
    "type": "other",
    "scope": null
  },
  {
    "sha": "333bf65c0ab3d64fc1891093c66ecb36f9257879",
    "shortSha": "333bf65",
    "dateIso": "2026-04-21T08:29:34+07:00",
    "author": "Bank",
    "subject": "fix: server components call Prisma directly instead of HTTP /api round-trip",
    "parents": "a5c87e9aa074c83edb6c0f563401c4dc1a811ff0",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "a5c87e9aa074c83edb6c0f563401c4dc1a811ff0",
    "shortSha": "a5c87e9",
    "dateIso": "2026-04-21T08:11:46+07:00",
    "author": "Bank",
    "subject": "fix: client fetches use /api/* relative; server-side fetch uses absolute base URL",
    "parents": "17d63311955de863e311ea10c02f2010559eff6a",
    "type": "fix",
    "scope": null
  },
  {
    "sha": "17d63311955de863e311ea10c02f2010559eff6a",
    "shortSha": "17d6331",
    "dateIso": "2026-04-21T07:58:24+07:00",
    "author": "Bank",
    "subject": "chore: trigger deploy on newly-connected webhook",
    "parents": "5f052263ca701fe9f194ae3a35d0c311e07a63e1",
    "type": "chore",
    "scope": null
  },
  {
    "sha": "5f052263ca701fe9f194ae3a35d0c311e07a63e1",
    "shortSha": "5f05226",
    "dateIso": "2026-04-21T07:54:22+07:00",
    "author": "Bank",
    "subject": "chore: trigger Vercel re-deploy after repo recreate",
    "parents": "ac139f6bba071e953eaa39c774b2ec9ad05490ab",
    "type": "chore",
    "scope": null
  },
  {
    "sha": "ac139f6bba071e953eaa39c774b2ec9ad05490ab",
    "shortSha": "ac139f6",
    "dateIso": "2026-04-21T06:49:39+07:00",
    "author": "Bank",
    "subject": "feat: METU digital marketplace — v2 dark-mode redesign + deploy-ready",
    "parents": "",
    "type": "feat",
    "scope": null
  }
] as const;
